"""Pipeline execution plan: the reviewable artifact between planning and execution.

A Plan is a serializable, immutable DAG of PlanJobs. It is:
  - Generated by ``build_plan()`` from topology + configs + current state
  - Reviewable by the user before committing GPU hours
  - Consumed by the orchestrator (reconciliation loop or fire-and-forget)
  - Diffable between runs to see what changed

The plan does NOT execute anything. It describes what SHOULD be executed.

Usage:
    plan = build_plan(dataset="hcrl_sa", seeds=[42, 123, 456])
    plan.save("plan.json")          # review it
    plan = Plan.load("plan.json")   # orchestrator consumes it
"""

from __future__ import annotations

import hashlib
import json
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from pydantic import BaseModel, Field

from .job import ResourceSpec


class ArtifactDependency(BaseModel, frozen=True):
    """A dependency on an artifact produced by another job in the plan."""

    job_id: str  # PlanJob.id of the producer
    artifact: str  # filename, e.g. "best_model.pt"
    as_field: str = ""  # how the consumer references it, e.g. "teacher_checkpoint"


class PlanJob(BaseModel, frozen=True):
    """One job in the execution plan.

    Contains everything needed to submit an sbatch: the stage, the frozen
    config overrides, resource requirements, and artifact dependencies.
    """

    id: str  # deterministic: "{model}_{scale}_{stage}[_{aux}]_seed{N}"
    stage: str
    model_type: str
    scale: str
    auxiliaries: str = "none"
    seed: int = 42

    # Config overrides beyond identity (e.g. teacher_path for KD)
    config_overrides: dict[str, Any] = {}

    # Dependencies
    depends_on: list[ArtifactDependency] = []

    # Resources (from resources.yaml)
    resources: ResourceSpec = ResourceSpec()

    # Expected outputs
    outputs: list[str] = Field(
        default=["best_model.pt", "config.json", "metrics.json"],
    )


class Plan(BaseModel, frozen=True):
    """A complete execution plan: reviewable, diffable, immutable.

    Generated by ``build_plan()``, serialized to JSON, consumed by the
    orchestrator. The plan_hash uniquely identifies the plan contents.
    """

    # Identity
    dataset: str
    seeds: list[int]
    created_at: str = Field(default_factory=lambda: datetime.now(UTC).isoformat())

    # The DAG
    jobs: list[PlanJob]

    # Metadata
    plan_hash: str = ""  # filled by build_plan after serialization
    topology_source: str = "pipeline.yaml"

    @property
    def job_ids(self) -> set[str]:
        return {j.id for j in self.jobs}

    @property
    def terminal_jobs(self) -> list[PlanJob]:
        """Jobs with no dependents (DAG leaves)."""
        depended_on = set()
        for job in self.jobs:
            for dep in job.depends_on:
                depended_on.add(dep.job_id)
        return [j for j in self.jobs if j.id not in depended_on]

    def job_by_id(self, job_id: str) -> PlanJob | None:
        return next((j for j in self.jobs if j.id == job_id), None)

    def save(self, path: str | Path) -> Path:
        """Write plan to JSON file."""
        p = Path(path)
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(self.model_dump_json(indent=2))
        return p

    @classmethod
    def load(cls, path: str | Path) -> Plan:
        """Load plan from JSON file."""
        return cls.model_validate_json(Path(path).read_text())


def _make_job_id(
    model_type: str,
    scale: str,
    stage: str,
    aux: str,
    seed: int,
) -> str:
    """Deterministic job ID."""
    model = "eval" if stage == "evaluation" else model_type
    suffix = f"_{aux}" if aux and aux != "none" else ""
    return f"{model}_{scale}_{stage}{suffix}_seed{seed}"


def build_plan(
    dataset: str,
    seeds: list[int],
    variant: str = "large",
) -> Plan:
    """Build an execution plan from pipeline topology + resources.

    Reads ``pipeline.yaml`` for DAG structure and ``resources.yaml`` for
    SLURM resource profiles. Produces a Plan with one PlanJob per
    stage × seed, wired with artifact dependencies.
    """
    from graphids.config import load_pipeline_yaml

    pipeline = load_pipeline_yaml()

    # Resolve variant
    variant_def = pipeline["variants"].get(variant)
    if variant_def is None:
        raise ValueError(f"Unknown variant '{variant}'. Available: {list(pipeline['variants'])}")

    scale = variant_def["scale"]
    aux = variant_def.get("auxiliaries", "none")
    variant_stages = variant_def["stages"]

    # Load resource profiles
    import yaml

    from graphids.config.handler import CONFIG_DIR

    resources_raw = yaml.safe_load((CONFIG_DIR / "resources.yaml").read_text())
    profiles = resources_raw.get("resource_profiles", {})

    # Build stage dependency map from pipeline.yaml
    stage_defs = pipeline["stages"]

    jobs: list[PlanJob] = []
    for seed in seeds:
        for stage_name in variant_stages:
            stage_def = stage_defs[stage_name]
            model_type = stage_def["model"]
            if model_type == "eval":
                model_type = "eval"

            job_id = _make_job_id(model_type, scale, stage_name, aux, seed)

            # Resolve artifact dependencies
            deps: list[ArtifactDependency] = []
            for dep_def in stage_def.get("depends_on", []):
                dep_model = dep_def["model"]
                dep_stage = dep_def["stage"]
                dep_job_id = _make_job_id(dep_model, scale, dep_stage, aux, seed)
                deps.append(
                    ArtifactDependency(
                        job_id=dep_job_id,
                        artifact="best_model.pt",
                        as_field=f"{dep_model}_{dep_stage}_checkpoint",
                    )
                )

            # Resolve resource profile
            resource_key = model_type if model_type != "eval" else "eval"
            profile_data = profiles.get(resource_key, {}).get(scale, {}).get(stage_name, {})
            resources = ResourceSpec.from_yaml(profile_data) if profile_data else ResourceSpec()

            # Config overrides for KD stages
            config_overrides: dict[str, Any] = {}
            if aux != "none" and variant_def.get("needs_teacher"):
                config_overrides["auxiliaries"] = aux

            jobs.append(
                PlanJob(
                    id=job_id,
                    stage=stage_name,
                    model_type=model_type,
                    scale=scale,
                    auxiliaries=aux,
                    seed=seed,
                    config_overrides=config_overrides,
                    depends_on=deps,
                    resources=resources,
                )
            )

    # Compute plan hash from job contents
    plan_data = json.dumps(
        [j.model_dump() for j in jobs],
        sort_keys=True,
        default=str,
    )
    plan_hash = hashlib.sha256(plan_data.encode()).hexdigest()[:12]

    return Plan(
        dataset=dataset,
        seeds=seeds,
        jobs=jobs,
        plan_hash=plan_hash,
    )
