"""Render a plan jsonnet to an executable bash artifact.

The plan is *data*; the bash script is the *action*. ``graphids run``
emits this script — it does not submit anything itself. The user
reviews, then executes via ``bash`` (or pipes ``| bash`` if trusted).

Each line is one ``graphids submit`` primitive call. ``afterok`` deps
thread via shell-variable capture: each line writes ``JID_<NAME>=$(...)``,
downstream lines read ``--dep "$JID_<UPSTREAM>"``.

Re-runnability: every preset line carries ``--skip-if-finished`` (default
ON, ``--force`` opts out) so MLflow short-circuits already-completed
nodes. A skipped node prints ``0``; downstream lines pass ``--dep "0"``,
which :func:`graphids.slurm.submit.submit` filters out before composing
the SLURM dependency string. Command-mode nodes don't get
``--skip-if-finished`` — they're not MLflow-tracked.
"""

from __future__ import annotations

import hashlib
import json
import shlex
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from collections.abc import Iterable

    from graphids.slurm.dag import Node


def _var_for(name: str) -> str:
    """``vgae-test`` → ``JID_VGAE_TEST``. Bash-safe identifier."""
    return "JID_" + name.upper().replace("-", "_")


def _plan_hash(nodes: Iterable[Node]) -> str:
    """8-hex-digit content hash of the toposorted plan. Header comment only."""
    payload = json.dumps(
        [
            {"name": n.name, "deps": list(n.deps), "preset": n.preset_path, "command": n.command}
            for n in nodes
        ],
        sort_keys=True,
    )
    return hashlib.sha256(payload.encode()).hexdigest()[:8]


def _preset_line(
    node: Node,
    *,
    dataset: str,
    seed: int,
    cluster: str,
    skip_finished: bool,
) -> str:
    """Render one ``graphids submit <preset>`` line."""
    parts = [
        "graphids submit",
        f"configs/ablations/{node.preset_path}",
        f"--dataset {dataset}",
        f"--seed {seed}",
        f"--cluster {cluster}",
    ]
    if node.action == "test":
        parts.append("--action test")
    if node.mode != "gpu":  # default is gpu; only emit overrides
        parts.append(f"--mode {node.mode}")
    if node.length != "long":
        parts.append(f"--length {node.length}")
    if node.mem_gb is not None:
        parts.append(f"--mem-gb {node.mem_gb}")
    if node.timeout_min is not None:
        parts.append(f"--timeout-min {node.timeout_min}")
    for dep_name in node.deps:
        parts.append(f'--dep "${_var_for(dep_name)}"')
    if skip_finished:
        parts.append("--skip-if-finished")
    inner = " \\\n    ".join(parts)
    return f"{_var_for(node.name)}=$({inner})"


def _command_line(node: Node, *, cluster: str) -> str:
    """Render one ``graphids submit --command "..."`` line."""
    assert node.command is not None
    parts = [
        "graphids submit",
        f"--command {shlex.quote(node.command)}",
        f"--mode {node.mode}",
        f"--cluster {cluster}",
    ]
    if node.mem_gb is not None:
        parts.append(f"--mem-gb {node.mem_gb}")
    if node.timeout_min is not None:
        parts.append(f"--timeout-min {node.timeout_min}")
    for dep_name in node.deps:
        parts.append(f'--dep "${_var_for(dep_name)}"')
    inner = " \\\n    ".join(parts)
    return f"{_var_for(node.name)}=$({inner})"


def render_plan_script(
    nodes: tuple[Node, ...],
    *,
    dataset: str,
    seed: int,
    cluster: str,
    skip_finished: bool = True,
    invocation: str | None = None,
) -> str:
    """Return an executable bash script that submits the toposorted plan.

    ``invocation`` is the original CLI line (for the header comment) — pass
    ``None`` for the default placeholder. Output is deterministic for a
    given (nodes, dataset, seed, cluster, skip_finished).
    """
    from graphids.slurm.dag import toposort

    ordered = toposort(nodes)
    header = [
        "#!/usr/bin/env bash",
        f"# Generated by: {invocation}" if invocation else "# Generated by `graphids run`",
        f"# {len(ordered)} nodes; plan_hash={_plan_hash(ordered)}",
        "set -euo pipefail",
        "",
    ]
    body: list[str] = []
    for node in ordered:
        if node.is_command:
            body.append(_command_line(node, cluster=cluster))
        else:
            body.append(
                _preset_line(
                    node,
                    dataset=dataset,
                    seed=seed,
                    cluster=cluster,
                    skip_finished=skip_finished,
                )
            )
        body.append("")
    return "\n".join(header + body)
