preprocessing_version: "7.0.0"
max_data_bytes: 8
excluded_attack_types: [suppress, masquerade]

slurm:
  account: PAS1266
  partition: gpu
  gpu_type: v100

ckpt_stages:
  vgae: autoencoder
  gat: curriculum
  dqn: fusion
  dgi: autoencoder
  temporal: temporal

ckpt_model:
  gat: gat
