preprocessing_version: "7.0.0"
max_data_bytes: 8
excluded_attack_types: [suppress, masquerade]

slurm:
  account: PAS1266
  partition: gpu
  gpu_type: v100
  log_dir: /fs/ess/PAS1266/kd-gat/slurm_logs

