# @package _global_
# VGAE small (student)
model_type: vgae
scale: small

vgae:
  hidden_dims: [80, 40, 16]
  latent_dim: 16
  heads: 1
  embedding_dim: 4
  dropout: 0.1
  conv_type: "gatv2"
  proj_dim: 32
training:
  lr: 0.002
  safety_factor: 0.85
