model:
  class_path: graphids.core.models.autoencoder.vgae.VGAEModule
  init_args:
    conv_type: gatv2
    edge_dim: 11
    variational: true
    mask_ratio: 0.3
    k_neg: 32
    canid_weight: 0.1
    nbr_weight: 0.05
    kl_weight: 0.01
    lr: 0.002
    compile_model: true
    gradient_checkpointing: true
    auxiliaries: []
