model:
  class_path: graphids.core.models.fusion.dqn.DQNFusionModule
  init_args:
    lr: 0.001
    decision_threshold: 0.5
    reward_kwargs:
      vgae_weights: [0.4, 0.3, 0.3]
    epsilon: 0.2
    epsilon_decay: 0.995
    min_epsilon: 0.01
    gpu_training_steps: 1
    weight_decay: 0.00001
    buffer_size: 50000
