model:
  init_args:
    scale: large
    spatial_hidden: 64
    spatial_layers: 3
    spatial_heads: 8
    spatial_dropout: 0.2
    spatial_embedding_dim: 16
    spatial_proj_dim: 48
    spatial_fc_layers: 4
    window_size: 10
    stride: 1
    temporal_hidden: 96
    temporal_heads: 8
    temporal_layers: 3
