resources:
  family: dgi
  by_scale:
    small:
      autoencoder: {mode: gpu_train, time: "2:00:00", mem: 40G, cpus: 8, workers: 6}
    large:
      autoencoder: {mode: gpu_train, time: "3:00:00", mem: 52G, cpus: 8, workers: 6}
