resources:
  family: dgi
  by_scale:
    small:
      autoencoder: {mode: gpu_train, time: "4:00:00", cpus: 8, workers: 6}
    large:
      autoencoder: {mode: gpu_train, time: "4:00:00", cpus: 8, workers: 6}
