#!/usr/bin/env python3
"""Add missing tools to the MLOps tools catalog.

Identifies well-known ML/HPC/research-data tools that are absent from the
existing 437-tool catalog and appends them with accurate metadata.
"""

import json
from pathlib import Path

CATALOG_PATH = Path.home() / "mlops_tools_catalog.json"

MISSING_TOOLS: list[dict] = [
    # ── HPC-native schedulers & workflow engines ──────────────────────
    {
        "name": "Flux Framework",
        "url": "https://flux-framework.org",
        "open_source": True,
        "categories": ["hpc", "orchestrator"],
        "license": "LGPL-3.0",
        "deployment_model": ["self_hosted"],
        "language_ecosystem": ["python", "c"],
        "maturity": "growth",
        "governance": "community",
        "integration_targets": ["slurm", "kubernetes"],
        "pipeline_stage": ["training"],
        "scale_profile": "multi_node",
    },
    {
        "name": "FireWorks",
        "url": "https://materialsproject.github.io/fireworks/",
        "open_source": True,
        "categories": ["workflow", "hpc"],
        "license": "BSD-3-Clause",
        "deployment_model": ["self_hosted"],
        "language_ecosystem": ["python"],
        "maturity": "production",
        "governance": "community",
        "integration_targets": ["mongodb", "slurm", "pbs"],
        "pipeline_stage": ["training", "preprocessing"],
        "scale_profile": "multi_node",
    },
    {
        "name": "Pegasus WMS",
        "url": "https://pegasus.isi.edu",
        "open_source": True,
        "categories": ["workflow", "hpc"],
        "license": "Apache-2.0",
        "deployment_model": ["self_hosted"],
        "language_ecosystem": ["python", "java"],
        "maturity": "production",
        "governance": "community",
        "integration_targets": ["condor", "slurm", "pbs", "globus"],
        "pipeline_stage": ["training", "preprocessing", "data_collection"],
        "scale_profile": "multi_node",
    },
    # ── Modern Python packaging ───────────────────────────────────────
    {
        "name": "uv",
        "url": "https://docs.astral.sh/uv/",
        "open_source": True,
        "categories": ["package_manager"],
        "license": "Apache-2.0",
        "deployment_model": ["self_hosted"],
        "language_ecosystem": ["python", "rust"],
        "maturity": "growth",
        "governance": "company_backed",
        "integration_targets": ["pip", "pypi", "virtualenv"],
        "pipeline_stage": [],
        "scale_profile": "single_node",
    },
    {
        "name": "Pixi",
        "url": "https://pixi.sh",
        "open_source": True,
        "categories": ["package_manager"],
        "license": "BSD-3-Clause",
        "deployment_model": ["self_hosted"],
        "language_ecosystem": ["python", "rust", "cpp"],
        "maturity": "growth",
        "governance": "company_backed",
        "integration_targets": ["conda-forge", "pypi"],
        "pipeline_stage": [],
        "scale_profile": "single_node",
    },
    {
        "name": "Rye",
        "url": "https://rye.astral.sh",
        "open_source": True,
        "categories": ["package_manager"],
        "license": "MIT",
        "deployment_model": ["self_hosted"],
        "language_ecosystem": ["python", "rust"],
        "maturity": "growth",
        "governance": "company_backed",
        "integration_targets": ["pip", "pypi"],
        "pipeline_stage": [],
        "scale_profile": "single_node",
    },
    {
        "name": "PDM",
        "url": "https://pdm-project.org",
        "open_source": True,
        "categories": ["package_manager"],
        "license": "MIT",
        "deployment_model": ["self_hosted"],
        "language_ecosystem": ["python"],
        "maturity": "production",
        "governance": "community",
        "integration_targets": ["pypi", "pep621"],
        "pipeline_stage": [],
        "scale_profile": "single_node",
    },
    {
        "name": "Hatch",
        "url": "https://hatch.pypa.io",
        "open_source": True,
        "categories": ["package_manager"],
        "license": "MIT",
        "deployment_model": ["self_hosted"],
        "language_ecosystem": ["python"],
        "maturity": "production",
        "governance": "community",
        "integration_targets": ["pypi", "pep621"],
        "pipeline_stage": [],
        "scale_profile": "single_node",
    },
    {
        "name": "conda",
        "url": "https://docs.conda.io",
        "open_source": True,
        "categories": ["package_manager"],
        "license": "BSD-3-Clause",
        "deployment_model": ["self_hosted"],
        "language_ecosystem": ["python", "r", "cpp"],
        "maturity": "production",
        "governance": "company_backed",
        "integration_targets": ["conda-forge", "anaconda"],
        "pipeline_stage": [],
        "scale_profile": "single_node",
    },
    {
        "name": "pip",
        "url": "https://pip.pypa.io",
        "open_source": True,
        "categories": ["package_manager"],
        "license": "MIT",
        "deployment_model": ["self_hosted"],
        "language_ecosystem": ["python"],
        "maturity": "production",
        "governance": "community",
        "integration_targets": ["pypi"],
        "pipeline_stage": [],
        "scale_profile": "single_node",
    },
    {
        "name": "mamba",
        "url": "https://mamba.readthedocs.io",
        "open_source": True,
        "categories": ["package_manager"],
        "license": "BSD-3-Clause",
        "deployment_model": ["self_hosted"],
        "language_ecosystem": ["python", "cpp"],
        "maturity": "production",
        "governance": "community",
        "integration_targets": ["conda-forge", "anaconda"],
        "pipeline_stage": [],
        "scale_profile": "single_node",
    },
    # ── Build tools & infra ───────────────────────────────────────────
    {
        "name": "Earthly",
        "url": "https://earthly.dev",
        "open_source": True,
        "categories": ["ci_cd", "containerization"],
        "license": "MPL-2.0",
        "deployment_model": ["self_hosted", "saas"],
        "language_ecosystem": ["go"],
        "maturity": "growth",
        "governance": "company_backed",
        "integration_targets": ["docker", "github_actions", "gitlab_ci"],
        "pipeline_stage": [],
        "scale_profile": "single_node",
    },
    {
        "name": "Dagger",
        "url": "https://dagger.io",
        "open_source": True,
        "categories": ["ci_cd", "containerization"],
        "license": "Apache-2.0",
        "deployment_model": ["self_hosted", "saas"],
        "language_ecosystem": ["go", "python", "typescript"],
        "maturity": "growth",
        "governance": "company_backed",
        "integration_targets": ["docker", "github_actions", "gitlab_ci"],
        "pipeline_stage": [],
        "scale_profile": "single_node",
    },
    {
        "name": "Bazel",
        "url": "https://bazel.build",
        "open_source": True,
        "categories": ["ci_cd"],
        "license": "Apache-2.0",
        "deployment_model": ["self_hosted"],
        "language_ecosystem": ["java", "python", "cpp", "go"],
        "maturity": "production",
        "governance": "foundation",
        "integration_targets": ["docker", "kubernetes"],
        "pipeline_stage": [],
        "scale_profile": "multi_node",
    },
    {
        "name": "Pants",
        "url": "https://www.pantsbuild.org",
        "open_source": True,
        "categories": ["ci_cd"],
        "license": "Apache-2.0",
        "deployment_model": ["self_hosted"],
        "language_ecosystem": ["python", "go", "java", "rust"],
        "maturity": "production",
        "governance": "community",
        "integration_targets": ["docker", "pypi"],
        "pipeline_stage": [],
        "scale_profile": "single_node",
    },
    {
        "name": "Nix",
        "url": "https://nixos.org",
        "open_source": True,
        "categories": ["package_manager", "config_management"],
        "license": "MIT",
        "deployment_model": ["self_hosted"],
        "language_ecosystem": ["nix"],
        "maturity": "production",
        "governance": "foundation",
        "integration_targets": ["docker", "nixpkgs"],
        "pipeline_stage": [],
        "scale_profile": "single_node",
    },
    # ── ML platforms ──────────────────────────────────────────────────
    {
        "name": "Modal",
        "url": "https://modal.com",
        "open_source": False,
        "categories": ["ml_platform", "distributed_computing"],
        "license": "Proprietary",
        "deployment_model": ["saas"],
        "language_ecosystem": ["python"],
        "maturity": "growth",
        "governance": "company_backed",
        "integration_targets": ["pytorch", "huggingface", "vllm"],
        "pipeline_stage": ["training", "serving"],
        "scale_profile": "multi_node",
    },
    {
        "name": "Anyscale",
        "url": "https://www.anyscale.com",
        "open_source": False,
        "categories": ["ml_platform", "distributed_computing"],
        "license": "Proprietary",
        "deployment_model": ["saas", "hybrid"],
        "language_ecosystem": ["python"],
        "maturity": "production",
        "governance": "company_backed",
        "integration_targets": ["ray", "kubernetes", "aws", "gcp"],
        "pipeline_stage": ["training", "serving"],
        "scale_profile": "multi_node",
    },
    # ── Notebooks ─────────────────────────────────────────────────────
    {
        "name": "Marimo",
        "url": "https://marimo.io",
        "open_source": True,
        "categories": ["notebook"],
        "license": "Apache-2.0",
        "deployment_model": ["self_hosted"],
        "language_ecosystem": ["python"],
        "maturity": "growth",
        "governance": "company_backed",
        "integration_targets": ["pandas", "polars", "plotly"],
        "pipeline_stage": ["preprocessing", "evaluation"],
        "scale_profile": "single_node",
    },
    {
        "name": "Hex",
        "url": "https://hex.tech",
        "open_source": False,
        "categories": ["notebook", "visualization"],
        "license": "Proprietary",
        "deployment_model": ["saas"],
        "language_ecosystem": ["python", "sql"],
        "maturity": "production",
        "governance": "company_backed",
        "integration_targets": ["snowflake", "databricks", "bigquery"],
        "pipeline_stage": ["preprocessing", "evaluation"],
        "scale_profile": "single_node",
    },
    {
        "name": "Deepnote",
        "url": "https://deepnote.com",
        "open_source": False,
        "categories": ["notebook"],
        "license": "Proprietary",
        "deployment_model": ["saas"],
        "language_ecosystem": ["python", "sql"],
        "maturity": "production",
        "governance": "company_backed",
        "integration_targets": ["snowflake", "bigquery", "postgres"],
        "pipeline_stage": ["preprocessing", "evaluation"],
        "scale_profile": "single_node",
    },
    {
        "name": "Jupyter Enterprise Gateway",
        "url": "https://jupyter-enterprise-gateway.readthedocs.io",
        "open_source": True,
        "categories": ["notebook", "distributed_computing"],
        "license": "BSD-3-Clause",
        "deployment_model": ["self_hosted"],
        "language_ecosystem": ["python"],
        "maturity": "production",
        "governance": "foundation",
        "integration_targets": ["jupyter", "kubernetes", "spark", "yarn"],
        "pipeline_stage": ["preprocessing", "training"],
        "scale_profile": "multi_node",
    },
    # ── ML frameworks (core, missing from catalog) ────────────────────
    {
        "name": "PyTorch",
        "url": "https://pytorch.org",
        "open_source": True,
        "categories": ["ml_framework"],
        "license": "BSD-3-Clause",
        "deployment_model": ["self_hosted"],
        "language_ecosystem": ["python", "cpp"],
        "maturity": "production",
        "governance": "linux_foundation",
        "integration_targets": ["cuda", "rocm", "onnx", "tensorboard"],
        "pipeline_stage": ["training", "evaluation", "serving"],
        "scale_profile": "multi_node",
    },
    {
        "name": "PyTorch Geometric (PyG)",
        "url": "https://pyg.org",
        "open_source": True,
        "categories": ["ml_framework"],
        "license": "MIT",
        "deployment_model": ["self_hosted"],
        "language_ecosystem": ["python"],
        "maturity": "production",
        "governance": "community",
        "integration_targets": ["pytorch", "cuda", "onnx"],
        "pipeline_stage": ["training", "evaluation", "preprocessing"],
        "scale_profile": "multi_node",
    },
    {
        "name": "PyTorch Lightning",
        "url": "https://lightning.ai/docs/pytorch/stable/",
        "open_source": True,
        "categories": ["ml_framework"],
        "license": "Apache-2.0",
        "deployment_model": ["self_hosted"],
        "language_ecosystem": ["python"],
        "maturity": "production",
        "governance": "company_backed",
        "integration_targets": ["pytorch", "tensorboard", "mlflow", "wandb"],
        "pipeline_stage": ["training", "evaluation"],
        "scale_profile": "multi_node",
    },
    {
        "name": "scikit-learn",
        "url": "https://scikit-learn.org",
        "open_source": True,
        "categories": ["ml_framework"],
        "license": "BSD-3-Clause",
        "deployment_model": ["self_hosted"],
        "language_ecosystem": ["python"],
        "maturity": "production",
        "governance": "community",
        "integration_targets": ["numpy", "scipy", "pandas", "onnx"],
        "pipeline_stage": ["training", "evaluation", "preprocessing"],
        "scale_profile": "single_node",
    },
    {
        "name": "XGBoost",
        "url": "https://xgboost.readthedocs.io",
        "open_source": True,
        "categories": ["ml_framework"],
        "license": "Apache-2.0",
        "deployment_model": ["self_hosted"],
        "language_ecosystem": ["python", "r", "java", "cpp"],
        "maturity": "production",
        "governance": "community",
        "integration_targets": ["spark", "dask", "ray", "cuda"],
        "pipeline_stage": ["training", "evaluation"],
        "scale_profile": "multi_node",
    },
    {
        "name": "LightGBM",
        "url": "https://lightgbm.readthedocs.io",
        "open_source": True,
        "categories": ["ml_framework"],
        "license": "MIT",
        "deployment_model": ["self_hosted"],
        "language_ecosystem": ["python", "r", "cpp"],
        "maturity": "production",
        "governance": "company_backed",
        "integration_targets": ["spark", "dask", "ray"],
        "pipeline_stage": ["training", "evaluation"],
        "scale_profile": "multi_node",
    },
    {
        "name": "CatBoost",
        "url": "https://catboost.ai",
        "open_source": True,
        "categories": ["ml_framework"],
        "license": "Apache-2.0",
        "deployment_model": ["self_hosted"],
        "language_ecosystem": ["python", "r", "cpp"],
        "maturity": "production",
        "governance": "company_backed",
        "integration_targets": ["spark", "onnx", "cuda"],
        "pipeline_stage": ["training", "evaluation"],
        "scale_profile": "single_node",
    },
    # ── Visualization ─────────────────────────────────────────────────
    {
        "name": "Plotly",
        "url": "https://plotly.com/python/",
        "open_source": True,
        "categories": ["visualization"],
        "license": "MIT",
        "deployment_model": ["self_hosted"],
        "language_ecosystem": ["python", "r", "javascript"],
        "maturity": "production",
        "governance": "company_backed",
        "integration_targets": ["jupyter", "dash", "streamlit"],
        "pipeline_stage": ["evaluation", "monitoring"],
        "scale_profile": "single_node",
    },
    {
        "name": "Panel",
        "url": "https://panel.holoviz.org",
        "open_source": True,
        "categories": ["visualization"],
        "license": "BSD-3-Clause",
        "deployment_model": ["self_hosted"],
        "language_ecosystem": ["python"],
        "maturity": "production",
        "governance": "company_backed",
        "integration_targets": ["bokeh", "matplotlib", "plotly", "jupyter"],
        "pipeline_stage": ["evaluation", "monitoring"],
        "scale_profile": "single_node",
    },
    {
        "name": "Voila",
        "url": "https://voila.readthedocs.io",
        "open_source": True,
        "categories": ["visualization", "notebook"],
        "license": "BSD-3-Clause",
        "deployment_model": ["self_hosted"],
        "language_ecosystem": ["python"],
        "maturity": "production",
        "governance": "community",
        "integration_targets": ["jupyter", "ipywidgets"],
        "pipeline_stage": ["evaluation"],
        "scale_profile": "single_node",
    },
    # ── Linters & code quality ────────────────────────────────────────
    {
        "name": "Ruff",
        "url": "https://docs.astral.sh/ruff/",
        "open_source": True,
        "categories": ["linter"],
        "license": "MIT",
        "deployment_model": ["self_hosted"],
        "language_ecosystem": ["python", "rust"],
        "maturity": "production",
        "governance": "company_backed",
        "integration_targets": ["pre-commit", "vscode", "github_actions"],
        "pipeline_stage": [],
        "scale_profile": "single_node",
    },
    {
        "name": "Black",
        "url": "https://black.readthedocs.io",
        "open_source": True,
        "categories": ["linter"],
        "license": "MIT",
        "deployment_model": ["self_hosted"],
        "language_ecosystem": ["python"],
        "maturity": "production",
        "governance": "community",
        "integration_targets": ["pre-commit", "vscode", "github_actions"],
        "pipeline_stage": [],
        "scale_profile": "single_node",
    },
    {
        "name": "mypy",
        "url": "https://mypy-lang.org",
        "open_source": True,
        "categories": ["linter"],
        "license": "MIT",
        "deployment_model": ["self_hosted"],
        "language_ecosystem": ["python"],
        "maturity": "production",
        "governance": "community",
        "integration_targets": ["pre-commit", "vscode", "github_actions"],
        "pipeline_stage": [],
        "scale_profile": "single_node",
    },
    {
        "name": "pre-commit",
        "url": "https://pre-commit.com",
        "open_source": True,
        "categories": ["linter", "ci_cd"],
        "license": "MIT",
        "deployment_model": ["self_hosted"],
        "language_ecosystem": ["python"],
        "maturity": "production",
        "governance": "community",
        "integration_targets": ["git", "ruff", "black", "mypy"],
        "pipeline_stage": [],
        "scale_profile": "single_node",
    },
    # ── Testing ───────────────────────────────────────────────────────
    {
        "name": "pytest",
        "url": "https://docs.pytest.org",
        "open_source": True,
        "categories": ["testing"],
        "license": "MIT",
        "deployment_model": ["self_hosted"],
        "language_ecosystem": ["python"],
        "maturity": "production",
        "governance": "community",
        "integration_targets": ["github_actions", "gitlab_ci", "jenkins"],
        "pipeline_stage": ["evaluation"],
        "scale_profile": "single_node",
    },
    # ── CI/CD ─────────────────────────────────────────────────────────
    {
        "name": "GitHub Actions",
        "url": "https://github.com/features/actions",
        "open_source": False,
        "categories": ["ci_cd"],
        "license": "Proprietary",
        "deployment_model": ["saas", "self_hosted"],
        "language_ecosystem": ["yaml"],
        "maturity": "production",
        "governance": "company_backed",
        "integration_targets": ["docker", "kubernetes", "aws", "gcp", "azure"],
        "pipeline_stage": [],
        "scale_profile": "multi_node",
    },
    # ── CLI frameworks ────────────────────────────────────────────────
    {
        "name": "Typer",
        "url": "https://typer.tiangolo.com",
        "open_source": True,
        "categories": ["cli_framework"],
        "license": "MIT",
        "deployment_model": ["self_hosted"],
        "language_ecosystem": ["python"],
        "maturity": "production",
        "governance": "community",
        "integration_targets": ["click", "rich"],
        "pipeline_stage": [],
        "scale_profile": "single_node",
    },
    {
        "name": "Click",
        "url": "https://click.palletsprojects.com",
        "open_source": True,
        "categories": ["cli_framework"],
        "license": "BSD-3-Clause",
        "deployment_model": ["self_hosted"],
        "language_ecosystem": ["python"],
        "maturity": "production",
        "governance": "community",
        "integration_targets": [],
        "pipeline_stage": [],
        "scale_profile": "single_node",
    },
    {
        "name": "Rich",
        "url": "https://rich.readthedocs.io",
        "open_source": True,
        "categories": ["cli_framework"],
        "license": "MIT",
        "deployment_model": ["self_hosted"],
        "language_ecosystem": ["python"],
        "maturity": "production",
        "governance": "community",
        "integration_targets": ["typer"],
        "pipeline_stage": [],
        "scale_profile": "single_node",
    },
    # ── Web frameworks / servers ──────────────────────────────────────
    {
        "name": "FastAPI",
        "url": "https://fastapi.tiangolo.com",
        "open_source": True,
        "categories": ["web_framework", "model_serving"],
        "license": "MIT",
        "deployment_model": ["self_hosted"],
        "language_ecosystem": ["python"],
        "maturity": "production",
        "governance": "community",
        "integration_targets": ["pydantic", "uvicorn", "docker"],
        "pipeline_stage": ["serving"],
        "scale_profile": "single_node",
    },
    {
        "name": "uvicorn",
        "url": "https://www.uvicorn.org",
        "open_source": True,
        "categories": ["web_framework"],
        "license": "BSD-3-Clause",
        "deployment_model": ["self_hosted"],
        "language_ecosystem": ["python"],
        "maturity": "production",
        "governance": "community",
        "integration_targets": ["fastapi", "starlette"],
        "pipeline_stage": ["serving"],
        "scale_profile": "single_node",
    },
    {
        "name": "Gunicorn",
        "url": "https://gunicorn.org",
        "open_source": True,
        "categories": ["web_framework"],
        "license": "MIT",
        "deployment_model": ["self_hosted"],
        "language_ecosystem": ["python"],
        "maturity": "production",
        "governance": "community",
        "integration_targets": ["flask", "django", "fastapi"],
        "pipeline_stage": ["serving"],
        "scale_profile": "single_node",
    },
    # ── Data science core libs ────────────────────────────────────────
    {
        "name": "NumPy",
        "url": "https://numpy.org",
        "open_source": True,
        "categories": ["ml_framework"],
        "license": "BSD-3-Clause",
        "deployment_model": ["self_hosted"],
        "language_ecosystem": ["python", "c"],
        "maturity": "production",
        "governance": "foundation",
        "integration_targets": ["scipy", "pandas", "pytorch", "tensorflow"],
        "pipeline_stage": ["preprocessing", "training", "evaluation"],
        "scale_profile": "single_node",
    },
    {
        "name": "SciPy",
        "url": "https://scipy.org",
        "open_source": True,
        "categories": ["ml_framework"],
        "license": "BSD-3-Clause",
        "deployment_model": ["self_hosted"],
        "language_ecosystem": ["python", "c", "fortran"],
        "maturity": "production",
        "governance": "foundation",
        "integration_targets": ["numpy", "scikit-learn"],
        "pipeline_stage": ["preprocessing", "training", "evaluation"],
        "scale_profile": "single_node",
    },
    {
        "name": "pandas",
        "url": "https://pandas.pydata.org",
        "open_source": True,
        "categories": ["data_management"],
        "license": "BSD-3-Clause",
        "deployment_model": ["self_hosted"],
        "language_ecosystem": ["python"],
        "maturity": "production",
        "governance": "foundation",
        "integration_targets": ["numpy", "sqlalchemy", "parquet", "csv"],
        "pipeline_stage": ["preprocessing", "data_collection", "evaluation"],
        "scale_profile": "single_node",
    },
    {
        "name": "matplotlib",
        "url": "https://matplotlib.org",
        "open_source": True,
        "categories": ["visualization"],
        "license": "PSF",
        "deployment_model": ["self_hosted"],
        "language_ecosystem": ["python"],
        "maturity": "production",
        "governance": "foundation",
        "integration_targets": ["numpy", "jupyter", "pandas"],
        "pipeline_stage": ["evaluation"],
        "scale_profile": "single_node",
    },
    {
        "name": "seaborn",
        "url": "https://seaborn.pydata.org",
        "open_source": True,
        "categories": ["visualization"],
        "license": "BSD-3-Clause",
        "deployment_model": ["self_hosted"],
        "language_ecosystem": ["python"],
        "maturity": "production",
        "governance": "community",
        "integration_targets": ["matplotlib", "pandas", "numpy"],
        "pipeline_stage": ["evaluation"],
        "scale_profile": "single_node",
    },
    # ── Additional well-known tools ───────────────────────────────────
    {
        "name": "TensorFlow",
        "url": "https://www.tensorflow.org",
        "open_source": True,
        "categories": ["ml_framework"],
        "license": "Apache-2.0",
        "deployment_model": ["self_hosted"],
        "language_ecosystem": ["python", "cpp", "javascript"],
        "maturity": "production",
        "governance": "company_backed",
        "integration_targets": ["cuda", "tpu", "onnx", "tensorboard", "keras"],
        "pipeline_stage": ["training", "evaluation", "serving"],
        "scale_profile": "multi_node",
    },
    {
        "name": "JAX",
        "url": "https://jax.readthedocs.io",
        "open_source": True,
        "categories": ["ml_framework"],
        "license": "Apache-2.0",
        "deployment_model": ["self_hosted"],
        "language_ecosystem": ["python"],
        "maturity": "production",
        "governance": "company_backed",
        "integration_targets": ["cuda", "tpu", "xla", "flax"],
        "pipeline_stage": ["training", "evaluation"],
        "scale_profile": "multi_node",
    },
    {
        "name": "Flax",
        "url": "https://flax.readthedocs.io",
        "open_source": True,
        "categories": ["ml_framework"],
        "license": "Apache-2.0",
        "deployment_model": ["self_hosted"],
        "language_ecosystem": ["python"],
        "maturity": "production",
        "governance": "company_backed",
        "integration_targets": ["jax", "tensorboard"],
        "pipeline_stage": ["training", "evaluation"],
        "scale_profile": "multi_node",
    },
    {
        "name": "Hugging Face Transformers",
        "url": "https://huggingface.co/docs/transformers",
        "open_source": True,
        "categories": ["ml_framework", "llm_tools"],
        "license": "Apache-2.0",
        "deployment_model": ["self_hosted"],
        "language_ecosystem": ["python"],
        "maturity": "production",
        "governance": "company_backed",
        "integration_targets": ["pytorch", "tensorflow", "jax", "onnx"],
        "pipeline_stage": ["training", "evaluation", "serving"],
        "scale_profile": "multi_node",
    },
    {
        "name": "SLURM",
        "url": "https://slurm.schedmd.com",
        "open_source": True,
        "categories": ["hpc", "orchestrator"],
        "license": "GPL-2.0",
        "deployment_model": ["self_hosted"],
        "language_ecosystem": ["c"],
        "maturity": "production",
        "governance": "company_backed",
        "integration_targets": ["mpi", "cuda", "singularity"],
        "pipeline_stage": ["training"],
        "scale_profile": "multi_node",
    },
    {
        "name": "Open MPI",
        "url": "https://www.open-mpi.org",
        "open_source": True,
        "categories": ["hpc", "distributed_computing"],
        "license": "BSD-3-Clause",
        "deployment_model": ["self_hosted"],
        "language_ecosystem": ["c", "cpp", "fortran", "python"],
        "maturity": "production",
        "governance": "community",
        "integration_targets": ["slurm", "pbs", "cuda"],
        "pipeline_stage": ["training"],
        "scale_profile": "multi_node",
    },
    {
        "name": "CUDA Toolkit",
        "url": "https://developer.nvidia.com/cuda-toolkit",
        "open_source": False,
        "categories": ["hpc", "distributed_computing"],
        "license": "Proprietary",
        "deployment_model": ["self_hosted"],
        "language_ecosystem": ["c", "cpp", "python"],
        "maturity": "production",
        "governance": "company_backed",
        "integration_targets": ["pytorch", "tensorflow", "jax"],
        "pipeline_stage": ["training", "serving"],
        "scale_profile": "multi_node",
    },
    {
        "name": "Globus",
        "url": "https://www.globus.org",
        "open_source": False,
        "categories": ["data_management", "hpc"],
        "license": "Proprietary",
        "deployment_model": ["saas", "self_hosted"],
        "language_ecosystem": ["python"],
        "maturity": "production",
        "governance": "foundation",
        "integration_targets": ["slurm", "s3", "hpc_clusters"],
        "pipeline_stage": ["data_collection"],
        "scale_profile": "multi_node",
    },
    {
        "name": "Singularity (SingularityCE)",
        "url": "https://sylabs.io/singularity/",
        "open_source": True,
        "categories": ["containerization", "hpc"],
        "license": "BSD-3-Clause",
        "deployment_model": ["self_hosted"],
        "language_ecosystem": ["go"],
        "maturity": "production",
        "governance": "company_backed",
        "integration_targets": ["slurm", "docker", "oci"],
        "pipeline_stage": ["training", "serving"],
        "scale_profile": "multi_node",
    },
    {
        "name": "Weights & Biases Sweeps",
        "url": "https://docs.wandb.ai/guides/sweeps",
        "open_source": False,
        "categories": ["hyperparameter_tuning"],
        "license": "Proprietary",
        "deployment_model": ["saas", "self_hosted"],
        "language_ecosystem": ["python"],
        "maturity": "production",
        "governance": "company_backed",
        "integration_targets": ["wandb", "pytorch", "tensorflow"],
        "pipeline_stage": ["training"],
        "scale_profile": "multi_node",
    },
    {
        "name": "DGL (Deep Graph Library)",
        "url": "https://www.dgl.ai",
        "open_source": True,
        "categories": ["ml_framework"],
        "license": "Apache-2.0",
        "deployment_model": ["self_hosted"],
        "language_ecosystem": ["python"],
        "maturity": "production",
        "governance": "company_backed",
        "integration_targets": ["pytorch", "tensorflow", "cuda"],
        "pipeline_stage": ["training", "evaluation"],
        "scale_profile": "multi_node",
    },
    {
        "name": "NetworkX",
        "url": "https://networkx.org",
        "open_source": True,
        "categories": ["data_management"],
        "license": "BSD-3-Clause",
        "deployment_model": ["self_hosted"],
        "language_ecosystem": ["python"],
        "maturity": "production",
        "governance": "community",
        "integration_targets": ["numpy", "scipy", "matplotlib"],
        "pipeline_stage": ["preprocessing", "evaluation"],
        "scale_profile": "single_node",
    },
    {
        "name": "ONNX",
        "url": "https://onnx.ai",
        "open_source": True,
        "categories": ["model_optimization", "serialization"],
        "license": "Apache-2.0",
        "deployment_model": ["self_hosted"],
        "language_ecosystem": ["python", "cpp"],
        "maturity": "production",
        "governance": "linux_foundation",
        "integration_targets": ["pytorch", "tensorflow", "onnx_runtime"],
        "pipeline_stage": ["serving", "evaluation"],
        "scale_profile": "single_node",
    },
    {
        "name": "Trivy",
        "url": "https://trivy.dev",
        "open_source": True,
        "categories": ["ci_cd"],
        "license": "Apache-2.0",
        "deployment_model": ["self_hosted"],
        "language_ecosystem": ["go"],
        "maturity": "production",
        "governance": "company_backed",
        "integration_targets": ["docker", "kubernetes", "github_actions"],
        "pipeline_stage": [],
        "scale_profile": "single_node",
    },
    {
        "name": "Grafana Loki",
        "url": "https://grafana.com/oss/loki/",
        "open_source": True,
        "categories": ["monitoring"],
        "license": "AGPL-3.0",
        "deployment_model": ["self_hosted", "saas"],
        "language_ecosystem": ["go"],
        "maturity": "production",
        "governance": "company_backed",
        "integration_targets": ["grafana", "prometheus", "kubernetes"],
        "pipeline_stage": ["monitoring"],
        "scale_profile": "multi_node",
    },
    {
        "name": "Weights & Biases Launch",
        "url": "https://docs.wandb.ai/guides/launch",
        "open_source": False,
        "categories": ["ml_platform", "orchestrator"],
        "license": "Proprietary",
        "deployment_model": ["saas", "self_hosted"],
        "language_ecosystem": ["python"],
        "maturity": "growth",
        "governance": "company_backed",
        "integration_targets": ["wandb", "kubernetes", "slurm"],
        "pipeline_stage": ["training"],
        "scale_profile": "multi_node",
    },
    {
        "name": "Litestar",
        "url": "https://litestar.dev",
        "open_source": True,
        "categories": ["web_framework"],
        "license": "MIT",
        "deployment_model": ["self_hosted"],
        "language_ecosystem": ["python"],
        "maturity": "growth",
        "governance": "community",
        "integration_targets": ["pydantic", "uvicorn", "sqlalchemy"],
        "pipeline_stage": ["serving"],
        "scale_profile": "single_node",
    },
    {
        "name": "tox",
        "url": "https://tox.wiki",
        "open_source": True,
        "categories": ["testing"],
        "license": "MIT",
        "deployment_model": ["self_hosted"],
        "language_ecosystem": ["python"],
        "maturity": "production",
        "governance": "community",
        "integration_targets": ["pytest", "virtualenv", "github_actions"],
        "pipeline_stage": [],
        "scale_profile": "single_node",
    },
    {
        "name": "nox",
        "url": "https://nox.thea.codes",
        "open_source": True,
        "categories": ["testing"],
        "license": "Apache-2.0",
        "deployment_model": ["self_hosted"],
        "language_ecosystem": ["python"],
        "maturity": "production",
        "governance": "community",
        "integration_targets": ["pytest", "virtualenv", "github_actions"],
        "pipeline_stage": [],
        "scale_profile": "single_node",
    },
    {
        "name": "Weights & Biases Weave",
        "url": "https://wandb.ai/site/weave",
        "open_source": True,
        "categories": ["experiment_tracking", "llm_tools"],
        "license": "Apache-2.0",
        "deployment_model": ["saas", "self_hosted"],
        "language_ecosystem": ["python"],
        "maturity": "growth",
        "governance": "company_backed",
        "integration_targets": ["wandb", "openai", "langchain"],
        "pipeline_stage": ["evaluation", "monitoring"],
        "scale_profile": "single_node",
    },
    {
        "name": "Parsl",
        "url": "https://parsl-project.org",
        "open_source": True,
        "categories": ["workflow", "hpc"],
        "license": "Apache-2.0",
        "deployment_model": ["self_hosted"],
        "language_ecosystem": ["python"],
        "maturity": "production",
        "governance": "community",
        "integration_targets": ["slurm", "condor", "kubernetes", "globus"],
        "pipeline_stage": ["training", "preprocessing"],
        "scale_profile": "multi_node",
    },
]


def main() -> None:
    with open(CATALOG_PATH) as f:
        catalog = json.load(f)

    existing_names = {tool["name"] for tool in catalog}

    added = []
    skipped = []
    for tool in MISSING_TOOLS:
        if tool["name"] in existing_names:
            skipped.append(tool["name"])
        else:
            catalog.append(tool)
            existing_names.add(tool["name"])
            added.append(tool["name"])

    with open(CATALOG_PATH, "w") as f:
        json.dump(catalog, f, indent=2)
        f.write("\n")

    print(f"Added {len(added)} tools to catalog (total now: {len(catalog)})")
    if skipped:
        print(f"Skipped {len(skipped)} already present: {', '.join(skipped)}")
    print()
    print("Tools added:")
    for name in sorted(added):
        print(f"  - {name}")


if __name__ == "__main__":
    main()
