#!/usr/bin/env python3
"""Enrich the MLOps tools catalog with 14 new evaluation dimensions.

Adds intelligent defaults based on existing fields, plus hand-curated values
for ~80 well-known tools relevant to HPC/ML research contexts.

Usage:
    python scripts/dev/enrich_catalog.py
"""

from __future__ import annotations

import json
from pathlib import Path

CATALOG_PATH = Path.home() / "mlops_tools_catalog.json"

# ── New dimension defaults ──────────────────────────────────────────────────

NEW_DIMENSIONS: dict = {
    "used_by": [],
    "hpc_compatible": "unknown",
    "collaboration_model": "unknown",
    "migration_cost": "unknown",
    "lock_in_risk": "unknown",
    "community_momentum": "unknown",
    "documentation_quality": "unknown",
    "python_native": False,
    "offline_capable": False,
    "resource_overhead": "unknown",
    "saas_available": False,
    "self_hosted_viable": False,
    "interoperability": "unknown",
    "summary": "",
}

# Categories that imply local/offline capability
OFFLINE_CATEGORIES = {
    "linter",
    "testing",
    "package_manager",
    "config",
    "cli_framework",
    "ml_framework",
    "explainability",
    "fairness",
    "automl",
    "hyperparameter_tuning",
    "visualization",
    "data_quality",
}

# Categories that imply lightweight resource overhead
LIBRARY_CATEGORIES = {
    "linter",
    "testing",
    "config",
    "cli_framework",
    "explainability",
    "fairness",
    "automl",
    "hyperparameter_tuning",
    "visualization",
    "data_quality",
}

# Categories implying heavier server infrastructure
SERVER_CATEGORIES = {
    "orchestrator",
    "ml_platform",
    "model_serving",
    "feature_store",
    "monitoring",
    "data_catalog",
    "ci_cd",
}

DISTRIBUTED_CATEGORIES = {
    "distributed_computing",
}

# ── Currently-used tools (set used_by=True) ──────────────────────────

CURRENTLY_USED = {
    "uv",
    "MLflow",
    "Ray",
    "Ray Tune",
    "Optuna",
    "PyTorch Lightning",
    "Lightning AI",  # may be listed as this
    "SLURM",
    "SQLite",
    "PostgreSQL",
    "DVC",
    "Hugging Face Hub",
    "Streamlit",
    "Plotly",
    "GitHub Actions",
    "Ruff",
    "pytest",
    "Docker",
    "Apptainer",
    "Apptainer (Singularity)",
    "Singularity",
    "Pydantic",
    "DuckDB",
}

# ── Well-known tool overrides ───────────────────────────────────────────────
# Keys are tool names (must match catalog). Values override any inferred defaults.
# fmt: off
WELL_KNOWN: dict[str, dict] = {
    # ── Currently used tools ──
    "uv": {
        "used_by": ["KD-GAT"],
        "hpc_compatible": "native",
        "collaboration_model": "single_user",
        "migration_cost": "low",
        "lock_in_risk": "low",
        "community_momentum": "growing",
        "documentation_quality": "excellent",
        "python_native": False,  # Rust binary
        "offline_capable": True,
        "resource_overhead": "minimal",
        "saas_available": False,
        "self_hosted_viable": True,
        "interoperability": "high",
        "summary": "Blazing-fast Python package manager/resolver. Drop-in pip replacement with 10-100x speedup; no lock-in since it reads standard pyproject.toml.",
    },
    "MLflow": {
        "used_by": ["KD-GAT"],
        "hpc_compatible": "native",
        "collaboration_model": "shared_server",
        "migration_cost": "medium",
        "lock_in_risk": "low",
        "community_momentum": "growing",
        "documentation_quality": "excellent",
        "python_native": True,
        "offline_capable": True,
        "resource_overhead": "moderate",
        "saas_available": True,
        "self_hosted_viable": True,
        "interoperability": "high",
        "summary": "Open-source experiment tracking with SQLite/PostgreSQL backend. Excellent for HPC (runs offline, file-based artifacts); migration risk is low since data is queryable SQL.",
    },
    "Ray": {
        "used_by": ["KD-GAT"],
        "hpc_compatible": "adaptable",
        "collaboration_model": "single_user",
        "migration_cost": "high",
        "lock_in_risk": "medium",
        "community_momentum": "growing",
        "documentation_quality": "excellent",
        "python_native": True,
        "offline_capable": True,
        "resource_overhead": "heavy",
        "saas_available": True,
        "self_hosted_viable": True,
        "interoperability": "medium",
        "summary": "Powerful distributed computing framework with native Tune/Train. Significant API surface creates moderate lock-in; head-node overhead can be heavy on shared HPC clusters.",
    },
    "Ray Tune": {
        "used_by": ["KD-GAT"],
        "hpc_compatible": "adaptable",
        "collaboration_model": "single_user",
        "migration_cost": "medium",
        "lock_in_risk": "medium",
        "community_momentum": "growing",
        "documentation_quality": "excellent",
        "python_native": True,
        "offline_capable": True,
        "resource_overhead": "heavy",
        "saas_available": True,
        "self_hosted_viable": True,
        "interoperability": "high",
        "summary": "Ray's HPO library with pluggable search (Optuna, HyperOpt). Great algorithm variety but tied to Ray runtime; consider Optuna standalone for simpler setups.",
    },
    "Optuna": {
        "used_by": ["KD-GAT"],
        "hpc_compatible": "native",
        "collaboration_model": "single_user",
        "migration_cost": "low",
        "lock_in_risk": "low",
        "community_momentum": "growing",
        "documentation_quality": "excellent",
        "python_native": True,
        "offline_capable": True,
        "resource_overhead": "minimal",
        "saas_available": False,
        "self_hosted_viable": True,
        "interoperability": "high",
        "summary": "Lightweight HPO library with SQLite/PostgreSQL storage for distributed trials. Perfect for HPC: no daemon, minimal overhead, works with any training loop.",
    },
    "Lightning AI": {
        "used_by": ["KD-GAT"],
        "hpc_compatible": "native",
        "collaboration_model": "single_user",
        "migration_cost": "medium",
        "lock_in_risk": "medium",
        "community_momentum": "growing",
        "documentation_quality": "excellent",
        "python_native": True,
        "offline_capable": True,
        "resource_overhead": "minimal",
        "saas_available": True,
        "self_hosted_viable": True,
        "interoperability": "high",
        "summary": "PyTorch Lightning training framework plus cloud platform. The library is excellent for HPC (SLURM-native, multi-GPU); the cloud platform is optional and not needed.",
    },
    "PyTorch Lightning": {
        "used_by": ["KD-GAT"],
        "hpc_compatible": "native",
        "collaboration_model": "single_user",
        "migration_cost": "medium",
        "lock_in_risk": "medium",
        "community_momentum": "growing",
        "documentation_quality": "excellent",
        "python_native": True,
        "offline_capable": True,
        "resource_overhead": "minimal",
        "saas_available": False,
        "self_hosted_viable": True,
        "interoperability": "high",
        "summary": "Structured PyTorch training with built-in SLURM support, checkpointing, and multi-GPU. Moderate lock-in due to LightningModule pattern, but training logic is portable.",
    },
    "SLURM": {
        "used_by": ["KD-GAT"],
        "hpc_compatible": "native",
        "collaboration_model": "multi_tenant",
        "migration_cost": "high",
        "lock_in_risk": "medium",
        "community_momentum": "stable",
        "documentation_quality": "adequate",
        "python_native": False,
        "offline_capable": True,
        "resource_overhead": "moderate",
        "saas_available": False,
        "self_hosted_viable": True,
        "interoperability": "high",
        "summary": "Dominant HPC job scheduler with excellent resource management. Deep integration into HPC ecosystem; migration to Flux or cloud is non-trivial but APIs are well-known.",
    },
    "SQLite": {
        "used_by": ["KD-GAT"],
        "hpc_compatible": "native",
        "collaboration_model": "single_user",
        "migration_cost": "low",
        "lock_in_risk": "low",
        "community_momentum": "stable",
        "documentation_quality": "excellent",
        "python_native": False,
        "offline_capable": True,
        "resource_overhead": "minimal",
        "saas_available": False,
        "self_hosted_viable": True,
        "interoperability": "high",
        "summary": "Embedded SQL database perfect for single-writer workloads. Zero-config, file-based; avoid on NFS with concurrent writers (use PostgreSQL instead).",
    },
    "PostgreSQL": {
        "used_by": ["KD-GAT"],
        "hpc_compatible": "adaptable",
        "collaboration_model": "shared_server",
        "migration_cost": "low",
        "lock_in_risk": "low",
        "community_momentum": "growing",
        "documentation_quality": "excellent",
        "python_native": False,
        "offline_capable": True,
        "resource_overhead": "moderate",
        "saas_available": True,
        "self_hosted_viable": True,
        "interoperability": "high",
        "summary": "Gold-standard relational database. On HPC, run via Apptainer on local SSD (not NFS). Excellent for multi-writer MLflow/orchestration backends.",
    },
    "DVC": {
        "used_by": ["KD-GAT"],
        "hpc_compatible": "native",
        "collaboration_model": "shared_server",
        "migration_cost": "low",
        "lock_in_risk": "low",
        "community_momentum": "stable",
        "documentation_quality": "excellent",
        "python_native": True,
        "offline_capable": True,
        "resource_overhead": "minimal",
        "saas_available": False,
        "self_hosted_viable": True,
        "interoperability": "high",
        "summary": "Git-based data versioning with remote storage support. Perfect for HPC: CLI-only, integrates with existing git workflow; large file tracking without Git LFS complexity.",
    },
    "Hugging Face Hub": {
        "used_by": ["KD-GAT"],
        "hpc_compatible": "adaptable",
        "collaboration_model": "multi_tenant",
        "migration_cost": "low",
        "lock_in_risk": "low",
        "community_momentum": "growing",
        "documentation_quality": "excellent",
        "python_native": True,
        "offline_capable": False,
        "resource_overhead": "minimal",
        "saas_available": True,
        "self_hosted_viable": True,
        "interoperability": "high",
        "summary": "Model/dataset hosting with git-based versioning. Excellent Python API for pushing artifacts; requires internet access but cached locally once downloaded.",
    },
    "Streamlit": {
        "used_by": ["KD-GAT"],
        "hpc_compatible": "adaptable",
        "collaboration_model": "shared_server",
        "migration_cost": "low",
        "lock_in_risk": "low",
        "community_momentum": "growing",
        "documentation_quality": "excellent",
        "python_native": True,
        "offline_capable": True,
        "resource_overhead": "moderate",
        "saas_available": True,
        "self_hosted_viable": True,
        "interoperability": "medium",
        "summary": "Fastest path from Python script to interactive dashboard. Great for sharing results via HF Spaces; limited customization compared to full web frameworks.",
    },
    "Plotly": {
        "used_by": ["KD-GAT"],
        "hpc_compatible": "native",
        "collaboration_model": "single_user",
        "migration_cost": "low",
        "lock_in_risk": "low",
        "community_momentum": "stable",
        "documentation_quality": "excellent",
        "python_native": True,
        "offline_capable": True,
        "resource_overhead": "minimal",
        "saas_available": True,
        "self_hosted_viable": True,
        "interoperability": "high",
        "summary": "Interactive plotting library with excellent Jupyter/Streamlit integration. Rich chart types; heavier than matplotlib but produces shareable HTML outputs.",
    },
    "GitHub Actions": {
        "used_by": ["KD-GAT"],
        "hpc_compatible": "cloud_only",
        "collaboration_model": "multi_tenant",
        "migration_cost": "medium",
        "lock_in_risk": "medium",
        "community_momentum": "growing",
        "documentation_quality": "excellent",
        "python_native": False,
        "offline_capable": False,
        "resource_overhead": "minimal",
        "saas_available": True,
        "self_hosted_viable": True,
        "interoperability": "high",
        "summary": "GitHub-native CI/CD with free tier for public repos. Easy YAML config; self-hosted runners enable HPC integration but workflow syntax is GitHub-specific.",
    },
    "Ruff": {
        "used_by": ["KD-GAT"],
        "hpc_compatible": "native",
        "collaboration_model": "single_user",
        "migration_cost": "low",
        "lock_in_risk": "low",
        "community_momentum": "growing",
        "documentation_quality": "excellent",
        "python_native": False,  # Rust binary
        "offline_capable": True,
        "resource_overhead": "minimal",
        "saas_available": False,
        "self_hosted_viable": True,
        "interoperability": "high",
        "summary": "Ultra-fast Python linter/formatter replacing flake8+isort+black. 10-100x faster; drop-in replacement with pyproject.toml config.",
    },
    "pytest": {
        "used_by": ["KD-GAT"],
        "hpc_compatible": "native",
        "collaboration_model": "single_user",
        "migration_cost": "low",
        "lock_in_risk": "low",
        "community_momentum": "stable",
        "documentation_quality": "excellent",
        "python_native": True,
        "offline_capable": True,
        "resource_overhead": "minimal",
        "saas_available": False,
        "self_hosted_viable": True,
        "interoperability": "high",
        "summary": "De facto Python testing framework with rich plugin ecosystem. Zero-overhead, fixture-based; essential for any Python project.",
    },
    "Docker": {
        "used_by": ["KD-GAT"],
        "hpc_compatible": "cloud_only",
        "collaboration_model": "single_user",
        "migration_cost": "low",
        "lock_in_risk": "low",
        "community_momentum": "stable",
        "documentation_quality": "excellent",
        "python_native": False,
        "offline_capable": True,
        "resource_overhead": "moderate",
        "saas_available": True,
        "self_hosted_viable": True,
        "interoperability": "high",
        "summary": "Industry-standard containerization. Not available on most HPC (requires root); use Apptainer to run Docker images rootlessly on HPC clusters.",
    },
    "Apptainer": {
        "used_by": ["KD-GAT"],
        "hpc_compatible": "native",
        "collaboration_model": "multi_tenant",
        "migration_cost": "low",
        "lock_in_risk": "low",
        "community_momentum": "growing",
        "documentation_quality": "adequate",
        "python_native": False,
        "offline_capable": True,
        "resource_overhead": "minimal",
        "saas_available": False,
        "self_hosted_viable": True,
        "interoperability": "high",
        "summary": "HPC-native container runtime (rootless, no daemon). Runs Docker images seamlessly; the standard for reproducible HPC workloads.",
    },
    "Apptainer (Singularity)": {
        "used_by": ["KD-GAT"],
        "hpc_compatible": "native",
        "collaboration_model": "multi_tenant",
        "migration_cost": "low",
        "lock_in_risk": "low",
        "community_momentum": "growing",
        "documentation_quality": "adequate",
        "python_native": False,
        "offline_capable": True,
        "resource_overhead": "minimal",
        "saas_available": False,
        "self_hosted_viable": True,
        "interoperability": "high",
        "summary": "HPC-native container runtime (rootless, no daemon). Runs Docker images seamlessly; the standard for reproducible HPC workloads.",
    },
    "Singularity": {
        "used_by": ["KD-GAT"],
        "hpc_compatible": "native",
        "collaboration_model": "multi_tenant",
        "migration_cost": "low",
        "lock_in_risk": "low",
        "community_momentum": "growing",
        "documentation_quality": "adequate",
        "python_native": False,
        "offline_capable": True,
        "resource_overhead": "minimal",
        "saas_available": False,
        "self_hosted_viable": True,
        "interoperability": "high",
        "summary": "HPC-native container runtime (rootless, no daemon). Renamed to Apptainer; still widely available on HPC clusters.",
    },
    "Pydantic": {
        "used_by": ["KD-GAT"],
        "hpc_compatible": "native",
        "collaboration_model": "single_user",
        "migration_cost": "low",
        "lock_in_risk": "low",
        "community_momentum": "growing",
        "documentation_quality": "excellent",
        "python_native": True,
        "offline_capable": True,
        "resource_overhead": "minimal",
        "saas_available": False,
        "self_hosted_viable": True,
        "interoperability": "high",
        "summary": "Fast data validation library using Python type hints. Essential for config management; v2's Rust core makes it production-grade with minimal overhead.",
    },
    "DuckDB": {
        "used_by": ["KD-GAT"],
        "hpc_compatible": "native",
        "collaboration_model": "single_user",
        "migration_cost": "low",
        "lock_in_risk": "low",
        "community_momentum": "growing",
        "documentation_quality": "excellent",
        "python_native": False,
        "offline_capable": True,
        "resource_overhead": "minimal",
        "saas_available": False,
        "self_hosted_viable": True,
        "interoperability": "high",
        "summary": "Embedded OLAP database with excellent Parquet/CSV support. Ideal for analytics on experiment data; zero-config, in-process, handles GB-scale data on a single node.",
    },
    # ── Experiment tracking competitors ──
    "Weights & Biases": {
        "hpc_compatible": "adaptable",
        "collaboration_model": "multi_tenant",
        "migration_cost": "medium",
        "lock_in_risk": "high",
        "community_momentum": "growing",
        "documentation_quality": "excellent",
        "python_native": True,
        "offline_capable": False,
        "resource_overhead": "moderate",
        "saas_available": True,
        "self_hosted_viable": True,
        "interoperability": "medium",
        "summary": "Best-in-class experiment tracking UI with sweeps and reports. Vendor lock-in risk is high (proprietary format); offline mode exists but is limited.",
    },
    "Neptune.ai": {
        "hpc_compatible": "adaptable",
        "collaboration_model": "multi_tenant",
        "migration_cost": "medium",
        "lock_in_risk": "high",
        "community_momentum": "stable",
        "documentation_quality": "excellent",
        "python_native": True,
        "offline_capable": False,
        "resource_overhead": "moderate",
        "saas_available": True,
        "self_hosted_viable": False,
        "interoperability": "medium",
        "summary": "SaaS experiment tracker with good metadata handling. No self-hosted option limits HPC use; strong UI but data is trapped in their platform.",
    },
    "ClearML": {
        "hpc_compatible": "adaptable",
        "collaboration_model": "shared_server",
        "migration_cost": "medium",
        "lock_in_risk": "medium",
        "community_momentum": "growing",
        "documentation_quality": "adequate",
        "python_native": True,
        "offline_capable": True,
        "resource_overhead": "moderate",
        "saas_available": True,
        "self_hosted_viable": True,
        "interoperability": "medium",
        "summary": "Full MLOps suite with experiment tracking, orchestration, and serving. Good self-hosted option; broad but shallow — jack of all trades vs. specialized tools.",
    },
    "Aim": {
        "hpc_compatible": "native",
        "collaboration_model": "single_user",
        "migration_cost": "low",
        "lock_in_risk": "low",
        "community_momentum": "stable",
        "documentation_quality": "adequate",
        "python_native": True,
        "offline_capable": True,
        "resource_overhead": "minimal",
        "saas_available": False,
        "self_hosted_viable": True,
        "interoperability": "medium",
        "summary": "Open-source experiment tracker with fast local UI. Great for solo HPC researchers (file-based storage); smaller community than MLflow but cleaner comparison UI.",
    },
    "Sacred": {
        "hpc_compatible": "native",
        "collaboration_model": "single_user",
        "migration_cost": "low",
        "lock_in_risk": "low",
        "community_momentum": "declining",
        "documentation_quality": "adequate",
        "python_native": True,
        "offline_capable": True,
        "resource_overhead": "minimal",
        "saas_available": False,
        "self_hosted_viable": True,
        "interoperability": "low",
        "summary": "Lightweight experiment config/logging with MongoDB backend. Largely superseded by MLflow/W&B; decorator-heavy API feels dated.",
    },
    "Guild AI": {
        "hpc_compatible": "native",
        "collaboration_model": "single_user",
        "migration_cost": "low",
        "lock_in_risk": "low",
        "community_momentum": "declining",
        "documentation_quality": "adequate",
        "python_native": True,
        "offline_capable": True,
        "resource_overhead": "minimal",
        "saas_available": False,
        "self_hosted_viable": True,
        "interoperability": "low",
        "summary": "CLI-first experiment tracker that captures runs automatically. Novel approach but small community; limited integrations compared to MLflow.",
    },
    "Comet ML": {
        "hpc_compatible": "adaptable",
        "collaboration_model": "multi_tenant",
        "migration_cost": "medium",
        "lock_in_risk": "high",
        "community_momentum": "stable",
        "documentation_quality": "excellent",
        "python_native": True,
        "offline_capable": False,
        "resource_overhead": "moderate",
        "saas_available": True,
        "self_hosted_viable": True,
        "interoperability": "medium",
        "summary": "SaaS experiment tracker with code diffing and rich media logging. Good UI but proprietary format creates lock-in; self-hosted option requires enterprise license.",
    },
    # ── Orchestrators ──
    "Metaflow": {
        "hpc_compatible": "adaptable",
        "collaboration_model": "single_user",
        "migration_cost": "high",
        "lock_in_risk": "medium",
        "community_momentum": "growing",
        "documentation_quality": "excellent",
        "python_native": True,
        "offline_capable": True,
        "resource_overhead": "minimal",
        "saas_available": False,
        "self_hosted_viable": True,
        "interoperability": "medium",
        "summary": "Netflix-born pipeline framework with excellent local dev experience. Decorator-based DAGs are elegant; AWS-oriented but local mode works well for HPC prototyping.",
    },
    "Prefect": {
        "hpc_compatible": "adaptable",
        "collaboration_model": "shared_server",
        "migration_cost": "medium",
        "lock_in_risk": "medium",
        "community_momentum": "growing",
        "documentation_quality": "excellent",
        "python_native": True,
        "offline_capable": True,
        "resource_overhead": "moderate",
        "saas_available": True,
        "self_hosted_viable": True,
        "interoperability": "high",
        "summary": "Modern workflow orchestrator with clean Python-native API. Self-hosted server works on HPC; Prefect Cloud adds UI but creates SaaS dependency.",
    },
    "Dagster": {
        "hpc_compatible": "adaptable",
        "collaboration_model": "shared_server",
        "migration_cost": "medium",
        "lock_in_risk": "medium",
        "community_momentum": "growing",
        "documentation_quality": "excellent",
        "python_native": True,
        "offline_capable": True,
        "resource_overhead": "moderate",
        "saas_available": True,
        "self_hosted_viable": True,
        "interoperability": "high",
        "summary": "Software-defined assets paradigm with excellent type checking and testing. More opinionated than Prefect; great for data engineering, overkill for simple ML pipelines.",
    },
    "Flyte": {
        "hpc_compatible": "adaptable",
        "collaboration_model": "shared_server",
        "migration_cost": "high",
        "lock_in_risk": "medium",
        "community_momentum": "growing",
        "documentation_quality": "adequate",
        "python_native": True,
        "offline_capable": False,
        "resource_overhead": "heavy",
        "saas_available": True,
        "self_hosted_viable": True,
        "interoperability": "medium",
        "summary": "Kubernetes-native workflow engine with strong typing and caching. Powerful for production ML but requires K8s infrastructure; too heavy for small HPC labs.",
    },
    "Kubeflow": {
        "hpc_compatible": "cloud_only",
        "collaboration_model": "multi_tenant",
        "migration_cost": "high",
        "lock_in_risk": "high",
        "community_momentum": "stable",
        "documentation_quality": "adequate",
        "python_native": True,
        "offline_capable": False,
        "resource_overhead": "heavy",
        "saas_available": True,
        "self_hosted_viable": True,
        "interoperability": "medium",
        "summary": "Full ML platform on Kubernetes with pipelines, notebooks, and serving. Massive infrastructure overhead; impractical for HPC without K8s.",
    },
    "ZenML": {
        "hpc_compatible": "adaptable",
        "collaboration_model": "shared_server",
        "migration_cost": "medium",
        "lock_in_risk": "medium",
        "community_momentum": "growing",
        "documentation_quality": "excellent",
        "python_native": True,
        "offline_capable": True,
        "resource_overhead": "moderate",
        "saas_available": True,
        "self_hosted_viable": True,
        "interoperability": "high",
        "summary": "Pipeline framework emphasizing stack abstraction (swap infra without code changes). Good concept but adds abstraction layer; growing community.",
    },
    "Apache Airflow": {
        "hpc_compatible": "adaptable",
        "collaboration_model": "shared_server",
        "migration_cost": "medium",
        "lock_in_risk": "medium",
        "community_momentum": "stable",
        "documentation_quality": "excellent",
        "python_native": True,
        "offline_capable": True,
        "resource_overhead": "heavy",
        "saas_available": True,
        "self_hosted_viable": True,
        "interoperability": "high",
        "summary": "Battle-tested workflow scheduler with massive ecosystem. Heavyweight (needs DB + webserver + scheduler); better for ETL than ML training pipelines.",
    },
    # ── Distributed / HPC ──
    "Dask": {
        "hpc_compatible": "native",
        "collaboration_model": "single_user",
        "migration_cost": "medium",
        "lock_in_risk": "low",
        "community_momentum": "stable",
        "documentation_quality": "excellent",
        "python_native": True,
        "offline_capable": True,
        "resource_overhead": "moderate",
        "saas_available": True,
        "self_hosted_viable": True,
        "interoperability": "high",
        "summary": "Pandas-like distributed computing with native SLURM integration (dask-jobqueue). Excellent for HPC data preprocessing; less suited for deep learning training.",
    },
    "Parsl": {
        "hpc_compatible": "native",
        "collaboration_model": "single_user",
        "migration_cost": "medium",
        "lock_in_risk": "low",
        "community_momentum": "stable",
        "documentation_quality": "adequate",
        "python_native": True,
        "offline_capable": True,
        "resource_overhead": "minimal",
        "saas_available": False,
        "self_hosted_viable": True,
        "interoperability": "medium",
        "summary": "Python-native parallel scripting designed for HPC. First-class SLURM/PBS support; smaller community than Dask but purpose-built for scientific computing.",
    },
    "Snakemake": {
        "hpc_compatible": "native",
        "collaboration_model": "single_user",
        "migration_cost": "medium",
        "lock_in_risk": "low",
        "community_momentum": "stable",
        "documentation_quality": "excellent",
        "python_native": True,
        "offline_capable": True,
        "resource_overhead": "minimal",
        "saas_available": False,
        "self_hosted_viable": True,
        "interoperability": "high",
        "summary": "Make-like workflow engine popular in bioinformatics with native SLURM support. File-based DAGs are intuitive; less Pythonic than Prefect/Dagster.",
    },
    "Nextflow": {
        "hpc_compatible": "native",
        "collaboration_model": "single_user",
        "migration_cost": "medium",
        "lock_in_risk": "medium",
        "community_momentum": "growing",
        "documentation_quality": "excellent",
        "python_native": False,
        "offline_capable": True,
        "resource_overhead": "moderate",
        "saas_available": True,
        "self_hosted_viable": True,
        "interoperability": "medium",
        "summary": "JVM-based workflow engine dominant in genomics. Excellent SLURM/container support; Groovy DSL is a barrier for Python-centric teams.",
    },
    "Luigi": {
        "hpc_compatible": "adaptable",
        "collaboration_model": "single_user",
        "migration_cost": "medium",
        "lock_in_risk": "low",
        "community_momentum": "declining",
        "documentation_quality": "adequate",
        "python_native": True,
        "offline_capable": True,
        "resource_overhead": "moderate",
        "saas_available": False,
        "self_hosted_viable": True,
        "interoperability": "medium",
        "summary": "Spotify's pipeline framework, predecessor to modern orchestrators. Stable but largely superseded by Prefect/Dagster; class-based tasks feel verbose.",
    },
    # ── Model serving ──
    "BentoML": {
        "hpc_compatible": "adaptable",
        "collaboration_model": "shared_server",
        "migration_cost": "medium",
        "lock_in_risk": "low",
        "community_momentum": "growing",
        "documentation_quality": "excellent",
        "python_native": True,
        "offline_capable": True,
        "resource_overhead": "moderate",
        "saas_available": True,
        "self_hosted_viable": True,
        "interoperability": "high",
        "summary": "Python-first model serving with automatic containerization. Clean API for packaging models; BentoCloud is optional, local serving works on HPC.",
    },
    "Seldon Core": {
        "hpc_compatible": "cloud_only",
        "collaboration_model": "multi_tenant",
        "migration_cost": "high",
        "lock_in_risk": "high",
        "community_momentum": "stable",
        "documentation_quality": "adequate",
        "python_native": False,
        "offline_capable": False,
        "resource_overhead": "heavy",
        "saas_available": True,
        "self_hosted_viable": True,
        "interoperability": "medium",
        "summary": "Kubernetes-native model serving with inference graphs. Powerful A/B testing and canary deployments; requires K8s, impractical for HPC.",
    },
    "KServe": {
        "hpc_compatible": "cloud_only",
        "collaboration_model": "multi_tenant",
        "migration_cost": "high",
        "lock_in_risk": "medium",
        "community_momentum": "growing",
        "documentation_quality": "adequate",
        "python_native": False,
        "offline_capable": False,
        "resource_overhead": "heavy",
        "saas_available": True,
        "self_hosted_viable": True,
        "interoperability": "high",
        "summary": "Kubernetes model serving standard (successor to KFServing). Good multi-framework support; requires K8s infrastructure.",
    },
    "Triton Inference Server": {
        "hpc_compatible": "native",
        "collaboration_model": "shared_server",
        "migration_cost": "medium",
        "lock_in_risk": "medium",
        "community_momentum": "growing",
        "documentation_quality": "excellent",
        "python_native": False,
        "offline_capable": True,
        "resource_overhead": "heavy",
        "saas_available": True,
        "self_hosted_viable": True,
        "interoperability": "high",
        "summary": "NVIDIA's high-performance inference server with dynamic batching and GPU optimization. Best raw throughput; complex setup but runs on HPC with GPU nodes.",
    },
    "TorchServe": {
        "hpc_compatible": "adaptable",
        "collaboration_model": "shared_server",
        "migration_cost": "medium",
        "lock_in_risk": "medium",
        "community_momentum": "stable",
        "documentation_quality": "adequate",
        "python_native": True,
        "offline_capable": True,
        "resource_overhead": "moderate",
        "saas_available": False,
        "self_hosted_viable": True,
        "interoperability": "medium",
        "summary": "Official PyTorch serving solution with model archiver. Good PyTorch integration but less mature than Triton; adequate for research-scale serving.",
    },
    "vLLM": {
        "hpc_compatible": "native",
        "collaboration_model": "single_user",
        "migration_cost": "low",
        "lock_in_risk": "low",
        "community_momentum": "growing",
        "documentation_quality": "adequate",
        "python_native": True,
        "offline_capable": True,
        "resource_overhead": "heavy",
        "saas_available": False,
        "self_hosted_viable": True,
        "interoperability": "medium",
        "summary": "Fastest open-source LLM inference engine with PagedAttention. Essential for LLM serving on GPU nodes; focused solely on text generation models.",
    },
    # ── Feature stores ──
    "Feast": {
        "hpc_compatible": "adaptable",
        "collaboration_model": "shared_server",
        "migration_cost": "medium",
        "lock_in_risk": "low",
        "community_momentum": "stable",
        "documentation_quality": "adequate",
        "python_native": True,
        "offline_capable": True,
        "resource_overhead": "moderate",
        "saas_available": False,
        "self_hosted_viable": True,
        "interoperability": "high",
        "summary": "Open-source feature store with offline/online serving. Good for teams sharing features; overkill for single-researcher setups where Parquet files suffice.",
    },
    "Tecton": {
        "hpc_compatible": "cloud_only",
        "collaboration_model": "multi_tenant",
        "migration_cost": "high",
        "lock_in_risk": "high",
        "community_momentum": "stable",
        "documentation_quality": "excellent",
        "python_native": True,
        "offline_capable": False,
        "resource_overhead": "heavy",
        "saas_available": True,
        "self_hosted_viable": False,
        "interoperability": "medium",
        "summary": "Enterprise feature platform by Feast creators. Powerful real-time features but SaaS-only and expensive; not viable for academic HPC.",
    },
    "Hopsworks": {
        "hpc_compatible": "adaptable",
        "collaboration_model": "multi_tenant",
        "migration_cost": "high",
        "lock_in_risk": "medium",
        "community_momentum": "stable",
        "documentation_quality": "adequate",
        "python_native": True,
        "offline_capable": False,
        "resource_overhead": "heavy",
        "saas_available": True,
        "self_hosted_viable": True,
        "interoperability": "medium",
        "summary": "Full ML platform with feature store at its core. Self-hosted option available but heavy (needs K8s or managed); better for teams than solo researchers.",
    },
    # ── Monitoring ──
    "Evidently": {
        "hpc_compatible": "native",
        "collaboration_model": "single_user",
        "migration_cost": "low",
        "lock_in_risk": "low",
        "community_momentum": "growing",
        "documentation_quality": "excellent",
        "python_native": True,
        "offline_capable": True,
        "resource_overhead": "minimal",
        "saas_available": True,
        "self_hosted_viable": True,
        "interoperability": "high",
        "summary": "Lightweight ML monitoring with drift detection and data quality reports. Perfect for research: runs as a library, generates HTML reports, no infrastructure needed.",
    },
    "NannyML": {
        "hpc_compatible": "native",
        "collaboration_model": "single_user",
        "migration_cost": "low",
        "lock_in_risk": "low",
        "community_momentum": "growing",
        "documentation_quality": "excellent",
        "python_native": True,
        "offline_capable": True,
        "resource_overhead": "minimal",
        "saas_available": True,
        "self_hosted_viable": True,
        "interoperability": "medium",
        "summary": "Performance estimation without ground truth using CBPE/DLE. Unique capability for monitoring deployed models; focused scope means fewer features than Evidently.",
    },
    "Prometheus": {
        "hpc_compatible": "adaptable",
        "collaboration_model": "shared_server",
        "migration_cost": "medium",
        "lock_in_risk": "low",
        "community_momentum": "stable",
        "documentation_quality": "excellent",
        "python_native": False,
        "offline_capable": True,
        "resource_overhead": "moderate",
        "saas_available": True,
        "self_hosted_viable": True,
        "interoperability": "high",
        "summary": "Industry-standard metrics collection with pull-based model. PromQL is powerful; heavy for HPC research use but essential for production infrastructure monitoring.",
    },
    "Grafana": {
        "hpc_compatible": "adaptable",
        "collaboration_model": "shared_server",
        "migration_cost": "low",
        "lock_in_risk": "low",
        "community_momentum": "growing",
        "documentation_quality": "excellent",
        "python_native": False,
        "offline_capable": True,
        "resource_overhead": "moderate",
        "saas_available": True,
        "self_hosted_viable": True,
        "interoperability": "high",
        "summary": "Best-in-class dashboarding with multi-datasource support. Overkill for HPC research but excellent if you already have Prometheus/InfluxDB infrastructure.",
    },
    "WhyLabs (whylogs)": {
        "hpc_compatible": "native",
        "collaboration_model": "single_user",
        "migration_cost": "low",
        "lock_in_risk": "low",
        "community_momentum": "growing",
        "documentation_quality": "adequate",
        "python_native": True,
        "offline_capable": True,
        "resource_overhead": "minimal",
        "saas_available": True,
        "self_hosted_viable": True,
        "interoperability": "high",
        "summary": "Lightweight data profiling library (whylogs) with optional SaaS dashboard. Library is great for HPC (zero-config profiling); WhyLabs platform is optional.",
    },
    # ── Data formats & engines ──
    "Polars": {
        "hpc_compatible": "native",
        "collaboration_model": "single_user",
        "migration_cost": "medium",
        "lock_in_risk": "low",
        "community_momentum": "growing",
        "documentation_quality": "excellent",
        "python_native": False,  # Rust core
        "offline_capable": True,
        "resource_overhead": "minimal",
        "saas_available": False,
        "self_hosted_viable": True,
        "interoperability": "high",
        "summary": "Blazing-fast DataFrame library in Rust. 5-10x faster than pandas for large data; lazy evaluation enables query optimization. Growing ecosystem.",
    },
    "Lance": {
        "hpc_compatible": "native",
        "collaboration_model": "single_user",
        "migration_cost": "low",
        "lock_in_risk": "low",
        "community_momentum": "growing",
        "documentation_quality": "adequate",
        "python_native": False,  # Rust core
        "offline_capable": True,
        "resource_overhead": "minimal",
        "saas_available": False,
        "self_hosted_viable": True,
        "interoperability": "medium",
        "summary": "Columnar data format optimized for ML (random access, versioning). Faster than Parquet for ML workloads; still young ecosystem.",
    },
    "LanceDB": {
        "hpc_compatible": "native",
        "collaboration_model": "single_user",
        "migration_cost": "low",
        "lock_in_risk": "low",
        "community_momentum": "growing",
        "documentation_quality": "adequate",
        "python_native": False,  # Rust core
        "offline_capable": True,
        "resource_overhead": "minimal",
        "saas_available": True,
        "self_hosted_viable": True,
        "interoperability": "medium",
        "summary": "Embedded vector database built on Lance format. Serverless, file-based; great for HPC embedding search without running a vector DB server.",
    },
    "Apache Iceberg": {
        "hpc_compatible": "adaptable",
        "collaboration_model": "shared_server",
        "migration_cost": "medium",
        "lock_in_risk": "low",
        "community_momentum": "growing",
        "documentation_quality": "excellent",
        "python_native": False,
        "offline_capable": True,
        "resource_overhead": "moderate",
        "saas_available": True,
        "self_hosted_viable": True,
        "interoperability": "high",
        "summary": "Open table format with ACID transactions and time travel. Industry momentum (Snowflake, Databricks adoption); heavy for small HPC labs, great for data lakes.",
    },
    "Delta Lake": {
        "hpc_compatible": "adaptable",
        "collaboration_model": "shared_server",
        "migration_cost": "medium",
        "lock_in_risk": "medium",
        "community_momentum": "stable",
        "documentation_quality": "excellent",
        "python_native": False,
        "offline_capable": True,
        "resource_overhead": "moderate",
        "saas_available": True,
        "self_hosted_viable": True,
        "interoperability": "high",
        "summary": "Databricks-originated table format with ACID and schema evolution. Strong Spark integration; Databricks association creates perception of lock-in despite being open source.",
    },
    "Apache Parquet": {
        "hpc_compatible": "native",
        "collaboration_model": "single_user",
        "migration_cost": "low",
        "lock_in_risk": "low",
        "community_momentum": "stable",
        "documentation_quality": "excellent",
        "python_native": False,
        "offline_capable": True,
        "resource_overhead": "minimal",
        "saas_available": False,
        "self_hosted_viable": True,
        "interoperability": "high",
        "summary": "Universal columnar file format with excellent compression. De facto standard for ML data; supported everywhere (pandas, DuckDB, Spark, Polars).",
    },
    # ── Config management ──
    "Hydra": {
        "hpc_compatible": "native",
        "collaboration_model": "single_user",
        "migration_cost": "medium",
        "lock_in_risk": "medium",
        "community_momentum": "stable",
        "documentation_quality": "excellent",
        "python_native": True,
        "offline_capable": True,
        "resource_overhead": "minimal",
        "saas_available": False,
        "self_hosted_viable": True,
        "interoperability": "medium",
        "summary": "Facebook's config framework with YAML composition and CLI overrides. Powerful but complex; Pydantic + YAML achieves similar results with less magic.",
    },
    "OmegaConf": {
        "hpc_compatible": "native",
        "collaboration_model": "single_user",
        "migration_cost": "low",
        "lock_in_risk": "low",
        "community_momentum": "stable",
        "documentation_quality": "adequate",
        "python_native": True,
        "offline_capable": True,
        "resource_overhead": "minimal",
        "saas_available": False,
        "self_hosted_viable": True,
        "interoperability": "medium",
        "summary": "YAML/dict config library underlying Hydra. Useful for config merging; largely superseded by Pydantic for validation-heavy use cases.",
    },
    # ── ML Platforms ──
    "Determined AI": {
        "hpc_compatible": "adaptable",
        "collaboration_model": "multi_tenant",
        "migration_cost": "high",
        "lock_in_risk": "high",
        "community_momentum": "stable",
        "documentation_quality": "excellent",
        "python_native": True,
        "offline_capable": True,
        "resource_overhead": "heavy",
        "saas_available": True,
        "self_hosted_viable": True,
        "interoperability": "medium",
        "summary": "ML platform with built-in distributed training and HPO. Good GPU cluster management; heavy infrastructure requirement and API lock-in for a small lab.",
    },
    "Modal": {
        "hpc_compatible": "cloud_only",
        "collaboration_model": "single_user",
        "migration_cost": "medium",
        "lock_in_risk": "high",
        "community_momentum": "growing",
        "documentation_quality": "excellent",
        "python_native": True,
        "offline_capable": False,
        "resource_overhead": "minimal",
        "saas_available": True,
        "self_hosted_viable": False,
        "interoperability": "low",
        "summary": "Serverless GPU compute with Python-native API. Amazing developer experience; fully cloud-only with high lock-in. Good for burst GPU needs beyond HPC allocation.",
    },
    "Amazon SageMaker": {
        "hpc_compatible": "cloud_only",
        "collaboration_model": "multi_tenant",
        "migration_cost": "high",
        "lock_in_risk": "high",
        "community_momentum": "stable",
        "documentation_quality": "excellent",
        "python_native": True,
        "offline_capable": False,
        "resource_overhead": "heavy",
        "saas_available": True,
        "self_hosted_viable": False,
        "interoperability": "medium",
        "summary": "AWS's full ML platform with notebooks, training, and deployment. Comprehensive but deeply AWS-locked; expensive and unsuitable for HPC-primary workflows.",
    },
    "Azure Machine Learning": {
        "hpc_compatible": "cloud_only",
        "collaboration_model": "multi_tenant",
        "migration_cost": "high",
        "lock_in_risk": "high",
        "community_momentum": "stable",
        "documentation_quality": "excellent",
        "python_native": True,
        "offline_capable": False,
        "resource_overhead": "heavy",
        "saas_available": True,
        "self_hosted_viable": False,
        "interoperability": "medium",
        "summary": "Microsoft's ML platform with good VS Code integration. Tightly coupled to Azure; academic discounts exist but HPC allocation is typically more cost-effective.",
    },
    "Google Cloud Vertex AI": {
        "hpc_compatible": "cloud_only",
        "collaboration_model": "multi_tenant",
        "migration_cost": "high",
        "lock_in_risk": "high",
        "community_momentum": "stable",
        "documentation_quality": "adequate",
        "python_native": True,
        "offline_capable": False,
        "resource_overhead": "heavy",
        "saas_available": True,
        "self_hosted_viable": False,
        "interoperability": "medium",
        "summary": "Google's unified ML platform (successor to AI Platform). Good TensorFlow integration; GCP-locked and documentation quality trails AWS/Azure.",
    },
    # ── Notebooks ──
    "Jupyter Notebook": {
        "hpc_compatible": "native",
        "collaboration_model": "single_user",
        "migration_cost": "low",
        "lock_in_risk": "low",
        "community_momentum": "stable",
        "documentation_quality": "excellent",
        "python_native": True,
        "offline_capable": True,
        "resource_overhead": "minimal",
        "saas_available": True,
        "self_hosted_viable": True,
        "interoperability": "high",
        "summary": "Ubiquitous interactive computing environment. Essential for exploration and visualization; not suitable for production code. Easy to run on HPC via SLURM.",
    },
    "JupyterLab": {
        "hpc_compatible": "native",
        "collaboration_model": "single_user",
        "migration_cost": "low",
        "lock_in_risk": "low",
        "community_momentum": "stable",
        "documentation_quality": "excellent",
        "python_native": True,
        "offline_capable": True,
        "resource_overhead": "moderate",
        "saas_available": True,
        "self_hosted_viable": True,
        "interoperability": "high",
        "summary": "Next-gen Jupyter with IDE-like features (file browser, terminals, extensions). Preferred over classic Notebook; OSC OnDemand provides managed JupyterLab instances.",
    },
    # ── Data quality ──
    "Great Expectations": {
        "hpc_compatible": "native",
        "collaboration_model": "single_user",
        "migration_cost": "medium",
        "lock_in_risk": "low",
        "community_momentum": "stable",
        "documentation_quality": "excellent",
        "python_native": True,
        "offline_capable": True,
        "resource_overhead": "minimal",
        "saas_available": True,
        "self_hosted_viable": True,
        "interoperability": "high",
        "summary": "Data validation framework with expectation suites and profiling. Comprehensive but complex setup; Pandera is simpler for pandas-centric validation.",
    },
    "Pandera": {
        "hpc_compatible": "native",
        "collaboration_model": "single_user",
        "migration_cost": "low",
        "lock_in_risk": "low",
        "community_momentum": "growing",
        "documentation_quality": "excellent",
        "python_native": True,
        "offline_capable": True,
        "resource_overhead": "minimal",
        "saas_available": False,
        "self_hosted_viable": True,
        "interoperability": "high",
        "summary": "Lightweight DataFrame validation with type annotations. Simpler than Great Expectations; integrates naturally with pandas/Polars workflows.",
    },
    # ── Table formats ──
    "Apache Hudi": {
        "hpc_compatible": "adaptable",
        "collaboration_model": "shared_server",
        "migration_cost": "medium",
        "lock_in_risk": "low",
        "community_momentum": "stable",
        "documentation_quality": "adequate",
        "python_native": False,
        "offline_capable": True,
        "resource_overhead": "heavy",
        "saas_available": True,
        "self_hosted_viable": True,
        "interoperability": "high",
        "summary": "Incremental data processing table format from Uber. Good for streaming updates; Spark-centric, less Python-friendly than Iceberg/Delta.",
    },
    # ── Infrastructure ──
    "Terraform": {
        "hpc_compatible": "cloud_only",
        "collaboration_model": "shared_server",
        "migration_cost": "medium",
        "lock_in_risk": "medium",
        "community_momentum": "stable",
        "documentation_quality": "excellent",
        "python_native": False,
        "offline_capable": True,
        "resource_overhead": "minimal",
        "saas_available": True,
        "self_hosted_viable": True,
        "interoperability": "high",
        "summary": "Infrastructure-as-code standard with multi-cloud support. Not relevant for HPC (no cloud provisioning); useful if lab also manages cloud resources.",
    },
    "Pulumi": {
        "hpc_compatible": "cloud_only",
        "collaboration_model": "shared_server",
        "migration_cost": "medium",
        "lock_in_risk": "medium",
        "community_momentum": "growing",
        "documentation_quality": "excellent",
        "python_native": True,
        "offline_capable": True,
        "resource_overhead": "minimal",
        "saas_available": True,
        "self_hosted_viable": True,
        "interoperability": "high",
        "summary": "IaC using real programming languages (Python, TypeScript). More intuitive than Terraform HCL for developers; same cloud-only limitation for HPC.",
    },
    "Helm": {
        "hpc_compatible": "cloud_only",
        "collaboration_model": "shared_server",
        "migration_cost": "medium",
        "lock_in_risk": "medium",
        "community_momentum": "stable",
        "documentation_quality": "excellent",
        "python_native": False,
        "offline_capable": True,
        "resource_overhead": "minimal",
        "saas_available": False,
        "self_hosted_viable": True,
        "interoperability": "medium",
        "summary": "Kubernetes package manager for templated deployments. Essential for K8s users; irrelevant for HPC without Kubernetes.",
    },
    "Kubernetes": {
        "hpc_compatible": "cloud_only",
        "collaboration_model": "multi_tenant",
        "migration_cost": "high",
        "lock_in_risk": "medium",
        "community_momentum": "stable",
        "documentation_quality": "excellent",
        "python_native": False,
        "offline_capable": True,
        "resource_overhead": "heavy",
        "saas_available": True,
        "self_hosted_viable": True,
        "interoperability": "high",
        "summary": "Container orchestration standard. Not available on traditional HPC; some centers are adopting K8s-on-HPC but SLURM remains dominant for batch workloads.",
    },
    # ── Version control / data ──
    "Git LFS": {
        "hpc_compatible": "native",
        "collaboration_model": "shared_server",
        "migration_cost": "low",
        "lock_in_risk": "low",
        "community_momentum": "stable",
        "documentation_quality": "adequate",
        "python_native": False,
        "offline_capable": True,
        "resource_overhead": "minimal",
        "saas_available": True,
        "self_hosted_viable": True,
        "interoperability": "high",
        "summary": "Git extension for large file tracking. Simple but limited (no deduplication, bandwidth-heavy); DVC is usually better for ML data versioning.",
    },
    "Dolt": {
        "hpc_compatible": "native",
        "collaboration_model": "shared_server",
        "migration_cost": "medium",
        "lock_in_risk": "low",
        "community_momentum": "growing",
        "documentation_quality": "excellent",
        "python_native": False,
        "offline_capable": True,
        "resource_overhead": "moderate",
        "saas_available": True,
        "self_hosted_viable": True,
        "interoperability": "medium",
        "summary": "Git-like versioned SQL database. Novel concept for dataset versioning with branch/merge semantics; niche but growing, MySQL-compatible wire protocol.",
    },
    # ── Additional well-known tools in catalog ──
    "Hyperopt": {
        "hpc_compatible": "native",
        "collaboration_model": "single_user",
        "migration_cost": "low",
        "lock_in_risk": "low",
        "community_momentum": "declining",
        "documentation_quality": "adequate",
        "python_native": True,
        "offline_capable": True,
        "resource_overhead": "minimal",
        "saas_available": False,
        "self_hosted_viable": True,
        "interoperability": "medium",
        "summary": "Early Bayesian HPO library with TPE and random search. Largely superseded by Optuna for new projects; MongoDB-backed distributed mode is clunky.",
    },
    "Katib": {
        "hpc_compatible": "cloud_only",
        "collaboration_model": "multi_tenant",
        "migration_cost": "high",
        "lock_in_risk": "high",
        "community_momentum": "stable",
        "documentation_quality": "adequate",
        "python_native": False,
        "offline_capable": False,
        "resource_overhead": "heavy",
        "saas_available": False,
        "self_hosted_viable": True,
        "interoperability": "medium",
        "summary": "Kubernetes-native HPO system from Kubeflow. Good for K8s environments; requires full Kubeflow stack, impractical for HPC.",
    },
    "TensorFlow Extended (TFX)": {
        "hpc_compatible": "adaptable",
        "collaboration_model": "single_user",
        "migration_cost": "high",
        "lock_in_risk": "high",
        "community_momentum": "declining",
        "documentation_quality": "adequate",
        "python_native": True,
        "offline_capable": True,
        "resource_overhead": "heavy",
        "saas_available": True,
        "self_hosted_viable": True,
        "interoperability": "low",
        "summary": "Google's end-to-end ML pipeline framework. Tightly coupled to TensorFlow ecosystem; declining momentum as PyTorch dominates research.",
    },
    "TensorBoard": {
        "hpc_compatible": "native",
        "collaboration_model": "single_user",
        "migration_cost": "low",
        "lock_in_risk": "low",
        "community_momentum": "stable",
        "documentation_quality": "excellent",
        "python_native": True,
        "offline_capable": True,
        "resource_overhead": "minimal",
        "saas_available": False,
        "self_hosted_viable": True,
        "interoperability": "high",
        "summary": "Standard training visualization tool. Works with PyTorch via SummaryWriter; lightweight and file-based. MLflow's UI largely replaces the need for separate TensorBoard.",
    },
    "TensorFlow Serving": {
        "hpc_compatible": "adaptable",
        "collaboration_model": "shared_server",
        "migration_cost": "medium",
        "lock_in_risk": "high",
        "community_momentum": "declining",
        "documentation_quality": "adequate",
        "python_native": False,
        "offline_capable": True,
        "resource_overhead": "moderate",
        "saas_available": True,
        "self_hosted_viable": True,
        "interoperability": "low",
        "summary": "TensorFlow's production serving system. TF-only; declining relevance as PyTorch dominates. Use Triton or BentoML for multi-framework serving.",
    },
    "Gradio": {
        "hpc_compatible": "adaptable",
        "collaboration_model": "single_user",
        "migration_cost": "low",
        "lock_in_risk": "low",
        "community_momentum": "growing",
        "documentation_quality": "excellent",
        "python_native": True,
        "offline_capable": True,
        "resource_overhead": "minimal",
        "saas_available": True,
        "self_hosted_viable": True,
        "interoperability": "medium",
        "summary": "Quick ML demo interface builder (owned by Hugging Face). Faster to prototype than Streamlit for model demos; more limited for general dashboards.",
    },
    "SHAP": {
        "hpc_compatible": "native",
        "collaboration_model": "single_user",
        "migration_cost": "low",
        "lock_in_risk": "low",
        "community_momentum": "stable",
        "documentation_quality": "excellent",
        "python_native": True,
        "offline_capable": True,
        "resource_overhead": "minimal",
        "saas_available": False,
        "self_hosted_viable": True,
        "interoperability": "high",
        "summary": "Shapley value-based model explanations. Theoretically grounded; can be slow for large models but essential for interpretability research.",
    },
    "Captum": {
        "hpc_compatible": "native",
        "collaboration_model": "single_user",
        "migration_cost": "low",
        "lock_in_risk": "low",
        "community_momentum": "stable",
        "documentation_quality": "adequate",
        "python_native": True,
        "offline_capable": True,
        "resource_overhead": "minimal",
        "saas_available": False,
        "self_hosted_viable": True,
        "interoperability": "medium",
        "summary": "PyTorch-native model interpretability library by Meta. Excellent PyTorch integration (GradCAM, IntegratedGradients); limited to PyTorch models.",
    },
    "Kedro": {
        "hpc_compatible": "native",
        "collaboration_model": "single_user",
        "migration_cost": "medium",
        "lock_in_risk": "medium",
        "community_momentum": "growing",
        "documentation_quality": "excellent",
        "python_native": True,
        "offline_capable": True,
        "resource_overhead": "minimal",
        "saas_available": False,
        "self_hosted_viable": True,
        "interoperability": "medium",
        "summary": "Opinionated ML project template from McKinsey (QuantumBlack). Clean data catalog pattern; heavier scaffolding than needed for small research projects.",
    },
    "CML": {
        "hpc_compatible": "adaptable",
        "collaboration_model": "shared_server",
        "migration_cost": "low",
        "lock_in_risk": "low",
        "community_momentum": "stable",
        "documentation_quality": "adequate",
        "python_native": False,
        "offline_capable": False,
        "resource_overhead": "minimal",
        "saas_available": False,
        "self_hosted_viable": True,
        "interoperability": "high",
        "summary": "CI/CD for ML by DVC team (reports in PRs). Great for GitHub-based ML workflows; limited without CI/CD infrastructure.",
    },
    "Polyaxon": {
        "hpc_compatible": "adaptable",
        "collaboration_model": "multi_tenant",
        "migration_cost": "high",
        "lock_in_risk": "high",
        "community_momentum": "declining",
        "documentation_quality": "adequate",
        "python_native": True,
        "offline_capable": False,
        "resource_overhead": "heavy",
        "saas_available": True,
        "self_hosted_viable": True,
        "interoperability": "medium",
        "summary": "Full ML platform with K8s orchestration. Was promising but community has declined; K8s dependency makes it unsuitable for HPC.",
    },
    "MLServer": {
        "hpc_compatible": "adaptable",
        "collaboration_model": "shared_server",
        "migration_cost": "low",
        "lock_in_risk": "low",
        "community_momentum": "growing",
        "documentation_quality": "adequate",
        "python_native": True,
        "offline_capable": True,
        "resource_overhead": "moderate",
        "saas_available": False,
        "self_hosted_viable": True,
        "interoperability": "high",
        "summary": "Seldon's open-source inference server implementing MLflow/V2 protocols. Lighter than Seldon Core (no K8s needed); good for simple serving.",
    },
    "Papermill": {
        "hpc_compatible": "native",
        "collaboration_model": "single_user",
        "migration_cost": "low",
        "lock_in_risk": "low",
        "community_momentum": "stable",
        "documentation_quality": "adequate",
        "python_native": True,
        "offline_capable": True,
        "resource_overhead": "minimal",
        "saas_available": False,
        "self_hosted_viable": True,
        "interoperability": "high",
        "summary": "Parameterized notebook execution from CLI. Great for SLURM-based notebook pipelines; simple concept, works well.",
    },
    "Deepchecks": {
        "hpc_compatible": "native",
        "collaboration_model": "single_user",
        "migration_cost": "low",
        "lock_in_risk": "low",
        "community_momentum": "stable",
        "documentation_quality": "excellent",
        "python_native": True,
        "offline_capable": True,
        "resource_overhead": "minimal",
        "saas_available": True,
        "self_hosted_viable": True,
        "interoperability": "high",
        "summary": "ML validation suite covering data integrity, drift, and model performance. Comprehensive checks out of the box; overlaps with Evidently.",
    },
    "Netron": {
        "hpc_compatible": "native",
        "collaboration_model": "single_user",
        "migration_cost": "low",
        "lock_in_risk": "low",
        "community_momentum": "stable",
        "documentation_quality": "adequate",
        "python_native": False,
        "offline_capable": True,
        "resource_overhead": "minimal",
        "saas_available": True,
        "self_hosted_viable": True,
        "interoperability": "high",
        "summary": "Neural network model visualizer supporting all major formats. Essential for inspecting model architectures; works as web app or desktop tool.",
    },
    "Argo Workflows": {
        "hpc_compatible": "cloud_only",
        "collaboration_model": "multi_tenant",
        "migration_cost": "high",
        "lock_in_risk": "medium",
        "community_momentum": "stable",
        "documentation_quality": "adequate",
        "python_native": False,
        "offline_capable": False,
        "resource_overhead": "heavy",
        "saas_available": False,
        "self_hosted_viable": True,
        "interoperability": "medium",
        "summary": "Kubernetes-native workflow engine with DAG support. Powerful for K8s environments; container-per-step model is expensive; not viable without K8s.",
    },
    "Pachyderm": {
        "hpc_compatible": "cloud_only",
        "collaboration_model": "multi_tenant",
        "migration_cost": "high",
        "lock_in_risk": "high",
        "community_momentum": "declining",
        "documentation_quality": "adequate",
        "python_native": False,
        "offline_capable": False,
        "resource_overhead": "heavy",
        "saas_available": True,
        "self_hosted_viable": True,
        "interoperability": "low",
        "summary": "Data versioning + pipeline platform on K8s. Novel git-like data approach but K8s dependency and declining community make it risky.",
    },
    "Label Studio": {
        "hpc_compatible": "adaptable",
        "collaboration_model": "shared_server",
        "migration_cost": "low",
        "lock_in_risk": "low",
        "community_momentum": "growing",
        "documentation_quality": "excellent",
        "python_native": True,
        "offline_capable": True,
        "resource_overhead": "moderate",
        "saas_available": True,
        "self_hosted_viable": True,
        "interoperability": "high",
        "summary": "Open-source data labeling platform with many annotation types. Self-hosted works well; good for creating labeled datasets for supervised learning.",
    },
    "H2O": {
        "hpc_compatible": "adaptable",
        "collaboration_model": "shared_server",
        "migration_cost": "medium",
        "lock_in_risk": "medium",
        "community_momentum": "stable",
        "documentation_quality": "excellent",
        "python_native": False,
        "offline_capable": True,
        "resource_overhead": "heavy",
        "saas_available": True,
        "self_hosted_viable": True,
        "interoperability": "medium",
        "summary": "AutoML platform with distributed training. Good for tabular ML; JVM-based runtime is heavy. Open source core but enterprise features require license.",
    },
    "NNI": {
        "hpc_compatible": "adaptable",
        "collaboration_model": "single_user",
        "migration_cost": "medium",
        "lock_in_risk": "low",
        "community_momentum": "declining",
        "documentation_quality": "adequate",
        "python_native": True,
        "offline_capable": True,
        "resource_overhead": "moderate",
        "saas_available": False,
        "self_hosted_viable": True,
        "interoperability": "medium",
        "summary": "Microsoft's HPO + NAS toolkit. Broad capabilities but development has slowed; Optuna is more actively maintained for HPO.",
    },
    "Fairlearn": {
        "hpc_compatible": "native",
        "collaboration_model": "single_user",
        "migration_cost": "low",
        "lock_in_risk": "low",
        "community_momentum": "stable",
        "documentation_quality": "excellent",
        "python_native": True,
        "offline_capable": True,
        "resource_overhead": "minimal",
        "saas_available": False,
        "self_hosted_viable": True,
        "interoperability": "high",
        "summary": "Microsoft's fairness assessment toolkit with mitigation algorithms. Well-maintained, scikit-learn compatible; essential for responsible AI research.",
    },
    "LIME": {
        "hpc_compatible": "native",
        "collaboration_model": "single_user",
        "migration_cost": "low",
        "lock_in_risk": "low",
        "community_momentum": "stable",
        "documentation_quality": "adequate",
        "python_native": True,
        "offline_capable": True,
        "resource_overhead": "minimal",
        "saas_available": False,
        "self_hosted_viable": True,
        "interoperability": "high",
        "summary": "Local interpretable model explanations via perturbation. Foundational explainability tool; simpler than SHAP but less theoretically grounded.",
    },
    "Alibi": {
        "hpc_compatible": "native",
        "collaboration_model": "single_user",
        "migration_cost": "low",
        "lock_in_risk": "low",
        "community_momentum": "stable",
        "documentation_quality": "excellent",
        "python_native": True,
        "offline_capable": True,
        "resource_overhead": "minimal",
        "saas_available": False,
        "self_hosted_viable": True,
        "interoperability": "high",
        "summary": "Seldon's explainability library with counterfactual explanations. Unique counterfactual and anchor methods; complements SHAP/LIME.",
    },
    "MLRun": {
        "hpc_compatible": "adaptable",
        "collaboration_model": "shared_server",
        "migration_cost": "high",
        "lock_in_risk": "high",
        "community_momentum": "stable",
        "documentation_quality": "adequate",
        "python_native": True,
        "offline_capable": False,
        "resource_overhead": "heavy",
        "saas_available": True,
        "self_hosted_viable": True,
        "interoperability": "medium",
        "summary": "Iguazio's open-source MLOps framework. Full pipeline management; heavy K8s dependency and company-backed with uncertain long-term open-source commitment.",
    },
    "Ploomber": {
        "hpc_compatible": "native",
        "collaboration_model": "single_user",
        "migration_cost": "low",
        "lock_in_risk": "low",
        "community_momentum": "stable",
        "documentation_quality": "adequate",
        "python_native": True,
        "offline_capable": True,
        "resource_overhead": "minimal",
        "saas_available": True,
        "self_hosted_viable": True,
        "interoperability": "medium",
        "summary": "Pipeline framework that works with notebooks and scripts. Low barrier to entry; Ploomber Cloud is optional.",
    },
    "DataRobot": {
        "hpc_compatible": "cloud_only",
        "collaboration_model": "multi_tenant",
        "migration_cost": "high",
        "lock_in_risk": "high",
        "community_momentum": "stable",
        "documentation_quality": "excellent",
        "python_native": True,
        "offline_capable": False,
        "resource_overhead": "heavy",
        "saas_available": True,
        "self_hosted_viable": True,
        "interoperability": "low",
        "summary": "Enterprise AutoML platform. Powerful for business ML but prohibitively expensive for academic use; heavy vendor lock-in.",
    },
    "lakeFS": {
        "hpc_compatible": "adaptable",
        "collaboration_model": "shared_server",
        "migration_cost": "medium",
        "lock_in_risk": "low",
        "community_momentum": "growing",
        "documentation_quality": "excellent",
        "python_native": False,
        "offline_capable": True,
        "resource_overhead": "moderate",
        "saas_available": True,
        "self_hosted_viable": True,
        "interoperability": "high",
        "summary": "Git-like data versioning for data lakes. Elegant branch/merge for object storage; adds operational complexity vs. DVC for small teams.",
    },
    "Marquez": {
        "hpc_compatible": "adaptable",
        "collaboration_model": "shared_server",
        "migration_cost": "medium",
        "lock_in_risk": "low",
        "community_momentum": "growing",
        "documentation_quality": "adequate",
        "python_native": False,
        "offline_capable": True,
        "resource_overhead": "moderate",
        "saas_available": False,
        "self_hosted_viable": True,
        "interoperability": "high",
        "summary": "OpenLineage-compatible data lineage service. Good for tracking data provenance; overkill for small research pipelines.",
    },
    "Quilt": {
        "hpc_compatible": "adaptable",
        "collaboration_model": "shared_server",
        "migration_cost": "medium",
        "lock_in_risk": "medium",
        "community_momentum": "stable",
        "documentation_quality": "adequate",
        "python_native": True,
        "offline_capable": False,
        "resource_overhead": "moderate",
        "saas_available": True,
        "self_hosted_viable": True,
        "interoperability": "medium",
        "summary": "Data package manager with S3-backed versioning. Interesting concept for data sharing; limited community and AWS-oriented.",
    },
    "Snorkel": {
        "hpc_compatible": "adaptable",
        "collaboration_model": "shared_server",
        "migration_cost": "medium",
        "lock_in_risk": "medium",
        "community_momentum": "declining",
        "documentation_quality": "adequate",
        "python_native": True,
        "offline_capable": False,
        "resource_overhead": "moderate",
        "saas_available": True,
        "self_hosted_viable": False,
        "interoperability": "low",
        "summary": "Programmatic data labeling via labeling functions. Innovative weak supervision approach; open-source version is unmaintained, SaaS-only going forward.",
    },
    "Feathr": {
        "hpc_compatible": "adaptable",
        "collaboration_model": "shared_server",
        "migration_cost": "medium",
        "lock_in_risk": "medium",
        "community_momentum": "declining",
        "documentation_quality": "adequate",
        "python_native": True,
        "offline_capable": False,
        "resource_overhead": "heavy",
        "saas_available": False,
        "self_hosted_viable": True,
        "interoperability": "medium",
        "summary": "LinkedIn's feature store donated to Linux Foundation. Spark-based; development has slowed significantly. Feast is a better choice.",
    },
    "OpenML": {
        "hpc_compatible": "adaptable",
        "collaboration_model": "multi_tenant",
        "migration_cost": "low",
        "lock_in_risk": "low",
        "community_momentum": "stable",
        "documentation_quality": "adequate",
        "python_native": True,
        "offline_capable": False,
        "resource_overhead": "minimal",
        "saas_available": True,
        "self_hosted_viable": False,
        "interoperability": "high",
        "summary": "Open platform for sharing ML experiments and datasets. Great for reproducibility research; SaaS-only but data is fully exportable.",
    },
    "Arize AI": {
        "hpc_compatible": "cloud_only",
        "collaboration_model": "multi_tenant",
        "migration_cost": "medium",
        "lock_in_risk": "high",
        "community_momentum": "growing",
        "documentation_quality": "excellent",
        "python_native": True,
        "offline_capable": False,
        "resource_overhead": "minimal",
        "saas_available": True,
        "self_hosted_viable": False,
        "interoperability": "medium",
        "summary": "SaaS model observability platform with drift detection and root cause analysis. Good UI but SaaS-only; use Evidently for open-source alternative.",
    },
    "Arize Phoenix": {
        "hpc_compatible": "native",
        "collaboration_model": "single_user",
        "migration_cost": "low",
        "lock_in_risk": "low",
        "community_momentum": "growing",
        "documentation_quality": "adequate",
        "python_native": True,
        "offline_capable": True,
        "resource_overhead": "minimal",
        "saas_available": False,
        "self_hosted_viable": True,
        "interoperability": "high",
        "summary": "Open-source observability for LLMs and ML (by Arize). Good for tracing and evaluating LLM outputs; lightweight local tool.",
    },
    "Ludwig": {
        "hpc_compatible": "adaptable",
        "collaboration_model": "single_user",
        "migration_cost": "medium",
        "lock_in_risk": "medium",
        "community_momentum": "stable",
        "documentation_quality": "excellent",
        "python_native": True,
        "offline_capable": True,
        "resource_overhead": "moderate",
        "saas_available": False,
        "self_hosted_viable": True,
        "interoperability": "medium",
        "summary": "Uber's declarative ML framework (YAML-driven training). Low-code approach is appealing but less flexible than writing training loops; built on Ray.",
    },
}
# fmt: on


def infer_defaults(tool: dict) -> dict:
    """Infer dimension values from existing tool fields."""
    dims = dict(NEW_DIMENSIONS)  # copy defaults

    categories = set(tool.get("categories", []))
    deployment = set(tool.get("deployment_model", []))
    languages = set(tool.get("language_ecosystem", []))
    scale = tool.get("scale_profile", "")

    # python_native
    if "python" in languages:
        dims["python_native"] = True

    # saas_available
    if "saas" in deployment or "managed_cloud" in deployment:
        dims["saas_available"] = True

    # self_hosted_viable
    if "self_hosted" in deployment or "embedded_library" in deployment:
        dims["self_hosted_viable"] = True

    # offline_capable
    if categories & OFFLINE_CATEGORIES:
        dims["offline_capable"] = True
    if "embedded_library" in deployment and not ("saas" in deployment and len(deployment) == 1):
        dims["offline_capable"] = True

    # hpc_compatible
    if categories & {"hpc", "hpc_scheduler"}:
        dims["hpc_compatible"] = "native"
    elif deployment == {"saas"} or deployment == {"managed_cloud"}:
        dims["hpc_compatible"] = "cloud_only"
    elif "self_hosted" in deployment or "embedded_library" in deployment:
        dims["hpc_compatible"] = "adaptable"

    # resource_overhead
    if "embedded_library" in deployment and not categories & SERVER_CATEGORIES:
        dims["resource_overhead"] = "minimal"
    elif categories & DISTRIBUTED_CATEGORIES or scale == "multi_node":
        dims["resource_overhead"] = "heavy"
    elif categories & SERVER_CATEGORIES:
        dims["resource_overhead"] = "moderate"
    elif categories & LIBRARY_CATEGORIES:
        dims["resource_overhead"] = "minimal"

    # collaboration_model (basic inference)
    if deployment == {"embedded_library"}:
        dims["collaboration_model"] = "single_user"
    elif "managed_cloud" in deployment or (
        "saas" in deployment and "multi_tenant" not in str(categories)
    ):
        dims["collaboration_model"] = "multi_tenant"

    return dims


def enrich_catalog() -> None:
    """Load catalog, add 14 new dimensions to every tool, save."""
    with open(CATALOG_PATH) as f:
        catalog: list[dict] = json.load(f)

    print(f"Loaded {len(catalog)} tools from {CATALOG_PATH}")

    # Track names for matching
    name_set = {t["name"] for t in catalog}

    # Check which currently-used tools are in the catalog
    found_used = CURRENTLY_USED & name_set
    missing_used = CURRENTLY_USED - name_set
    if missing_used:
        print(f"\nNote: These currently-used tools are NOT in the catalog: {sorted(missing_used)}")
    print(f"Currently-used tools found in catalog: {len(found_used)}")

    # Check which well-known tools are in the catalog
    found_known = set(WELL_KNOWN.keys()) & name_set
    missing_known = set(WELL_KNOWN.keys()) - name_set
    if missing_known:
        print(f"Note: These well-known tools are NOT in the catalog: {sorted(missing_known)}")
    print(f"Well-known tools found in catalog: {len(found_known)}")

    # Enrich each tool
    used_by_count = 0
    for tool in catalog:
        name = tool["name"]

        # Start with inferred defaults
        dims = infer_defaults(tool)

        # Override with well-known values if available
        if name in WELL_KNOWN:
            for k, v in WELL_KNOWN[name].items():
                dims[k] = v

        # Set used_by for matching tools
        if name in CURRENTLY_USED:
            dims["used_by"] = ["KD-GAT"]
            used_by_count += 1

        # Add dimensions to tool (only new keys)
        for k, v in dims.items():
            if k not in tool:
                tool[k] = v

    # Save
    with open(CATALOG_PATH, "w") as f:
        json.dump(catalog, f, indent=2, ensure_ascii=False)
        f.write("\n")

    print(f"\nSaved enriched catalog to {CATALOG_PATH}")
    print(f"Tools marked as used_by: {used_by_count}")

    # ── Statistics ──────────────────────────────────────────────────────────
    print("\n" + "=" * 70)
    print("ENRICHMENT STATISTICS")
    print("=" * 70)
    print(f"Total tools enriched: {len(catalog)}")
    print()

    dimension_names = list(NEW_DIMENSIONS.keys())
    for dim in dimension_names:
        default_val = NEW_DIMENSIONS[dim]
        non_default = sum(1 for t in catalog if t.get(dim) != default_val)
        pct = non_default / len(catalog) * 100
        print(f"  {dim:25s}: {non_default:4d}/{len(catalog)} non-default ({pct:5.1f}%)")

    # Count tools with ALL dimensions non-unknown/non-default
    fully_populated = 0
    for tool in catalog:
        all_set = True
        for dim in dimension_names:
            val = tool.get(dim)
            if val == "unknown" or val == "" or val is None:
                all_set = False
                break
        if all_set:
            fully_populated += 1
    print(f"\n  Fully populated (no 'unknown'/empty): {fully_populated}/{len(catalog)}")

    # Show currently-used tools
    print(f"\n  Currently used tools ({used_by_count}):")
    for tool in catalog:
        if tool.get("used_by"):
            print(f"    - {tool['name']}")


if __name__ == "__main__":
    enrich_catalog()
