stage:
  name: autoencoder
  trainer_overrides: {}
  callbacks_overrides: {}
data:
  class_path: CANBusDataModule
  init_args:
    window_size: 100
    stride: 100
    val_fraction: 0.2
    batch_size: 8192
    num_workers: 2
    dynamic_batching: true
