data:
  class_path: graphids.core.preprocessing.datamodule.CANBusDataModule
  init_args:
    window_size: 100
    stride: 100
    val_fraction: 0.2
    batch_size: 8192
    num_workers: 6
    dynamic_batching: true
